FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント ハジツゲかいじょうへ\nようこそ おいでなされた!\pこちらでは かちぬきチームバトルの\nあんないを しておりますぞ!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}かちぬきチームバトルに\nちょうせん されますかな?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "{JPN}またの ちょうせんを\nおまちして おりますぞ!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "{JPN}バトルテント ハジツゲかいじょうでは\nかちぬきチームバトルを\lおこなって おりますぞ!\pさんかする かたには しゅつじょう させる\n3ひきの ポケモンと たたかいに だす\lじゅんばんを きめて いただきますぞ!\pたたかいの あいだは\nこの じゅんばん どおりに\lポケモンを だすことに なりますな!\pたたかいに いちど だした ポケモンは\nけっちゃくが つくまで\lこうたいさせる ことが できませぬ!\pさらに 3ターン いないに\nたたかいの けっちゃくが つかなければ\lはんていと なりますぞ!\pまた とちゅうで ちょうせんを\nちゅうだんしたい ばあいは\lレポートを かかないと\lつづけて ちょうせんが できないので\lおきをつけ くだされ!\pみごと 3にんぬきを なされた あかつきには\nすてきな しょうひんを\lおおくり いたしますぞ!$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ おつれする まえに\nレポートを かきますが よろしいですかな?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と レベル100の へやが\nありますが どちらに まいられますかな?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}では ちょうせんする ポケモンを\n3ひき おえらび くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}おきゃくじん!!\pさんかできる ポケモンが\n3ひき おりませんぬ!\pまた もたせる どうぐも\nすべて ちがう どうぐに してくだされ!\pなお タマゴ{STR_VAR_1}さんか させる ことは できませぬ!\pじゅんびが できましたら\nまた おこし くだされ!$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}おきゃくじん!!\pさんかできる ポケモンが\n3ひき おりませぬ!\pさんかする ためには\nすべて ちがう しゅるいの ポケモンを\l3ひき よういして くだされ\pまた もたせる どうぐも\nすべて ちがう どうぐに してくだされ!\pなお タマゴ{STR_VAR_1}さんか させる ことは できませぬ!\pじゅんびが できましたら\nまた おこし くだされ!$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "{JPN}では バトルテントへ\nおつれいたしますぞ!$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}おきゃくじん!\pぜんかい レポートを かいて\nしゅうりょう しませんでしたな?\pざんねんですが その ばあい\nちょうせんは むこうと なりますぞ!\pまた はじめから\nちょうせん してくだされ!!$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "{JPN}3にんぬき たっせい\nおみごとで ございました!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "{JPN}レポートを かきますので\nおまちくだされ!$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3にんぬきを たっせい されましたので\nこの しょうひんを おうけとり くだされ!$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は\n{STR_VAR_1}を もらった!$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "{JPN}……おおっ!\nどうぐが いっぱいの ようですな!\pどうぐを せいりしてから\nまた おこしくだされ!$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "{JPN}おつかれさまでした!\pレポートを かきますので\nおまちくだされ!$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "{JPN}またの ちょうせんを\nおまちして おりますぞ!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "{JPN}おまちしておりました!\pバトルテントに おつれする まえに\nレポートを かきますので おまちくだされ!$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント\nシダケかいじょうへ ようこそ\pここでは トレーナーの\nしんらいの こころを ためしておる$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}バトルテント シダケかいじょうに\nちょうせん するか?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "{JPN}バトルテント シダケかいじょうでの\nたたかいには まもらなければ ならない\lひとつの おきてが ある\pここでは ポケモンは\nいれかえ しか できない!\pそれいがいの めいれいは\nいっさい きんし して おるのだ!\pポケモンには おのれの せいかくの ままに\nかんがえ こうどう して もらう!\pおぬしは じぶんの\nポケモンたちを しんじて\lたたかいを みまもって やれ\pみごと 3にんの トレーナーを\nうちやぶることが できれば\lしょうひんを さしあげよう\pまた とちゅうで ちょうせんを\nちゅうだん したい ときは\lきちんと レポートを かかないと\lつづけて ちょうせん できん からな\lきを つけてくれ……$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "{JPN}おのれの こころと ポケモンを きたえたら\nまた くるがよい……$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50の へやと レベル100の へやが\nあるが どちらに ちょうせん するのだ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{JPN}おぬし……\pちょうせん できる ポケモンが\n3ひき おらんぞ!\pちょうせん するには\nすべて ちがう しゅるいの ポケモンを\l3ひき ようい してくれ\pまた もたせる どうぐも\nすべて ちがう もので なければ いかん\pなお タマゴ{STR_VAR_1}ちょうせん させる ことは できん!\pじゅんびを ととのえてから また きなさい$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{JPN}おぬし……\pちょうせん できる ポケモンが\n3ひき おらんぞ!\pちょうせん するには\nすべて ちがう しゅるいの ポケモンを\p3ひき ようい してくれ\pまた もたせる どうぐも\nすべて ちがう もので なければ いかん\pそして タマゴ{STR_VAR_1}ちょうせん\nさせる ことは できん!\pじゅんびを ととえてから また きなさい$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "{JPN}では ちょうせんする ポケモンを\n3ひき えらんでくれ$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}バトルテントへ むかうまえに\nレポートを かくが よろしいか?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "{JPN}それでは\nわしに ついてこい……$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "{JPN}よいものを みせて もらった\pそれでは レポートを かこう……\nしばし またれよ……$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "{JPN}3にんぬき たっせい とは……\pおぬしと ポケモンの こころの きずなは\nまことの ようじゃな……$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "{JPN}レポートに かくぞ\nしばし またれよ……$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "{JPN}3にんぬきの あかしに\nこちらを さしあげよう……$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "{JPN}バトルテント カイナかいじょうへ\nようこそ!\pバトルトレードの\nごあんないは こちらです!$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "{JPN}バトルトレードに\nちょうせん しますか?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "{JPN}バトルテント カイナかいじょうでは\nレンタルポケモンを つかった\lバトルトレード という イベントを\lおこなっています!\pまずは バトルトレード せんようの\nポケモン 3ひきを おかし します!\pつぎに そちらの 3ひきの ポケモンを\nつかって シングルバトルを\lおこなって いただきます!\pみごと たたかいに しょうりすると\nたたかった トレーナーと ポケモンを\lトレード することが できます!\pトレードと たたかいを くりかえし\nみごと 3れんしょう したら\lすてきな しょうひんを さしあげます!\pなお とちゅうで ちょうせんを\nちゅうだん したい ときには\lきちんと レポートを かかないと\lつづけて ちょうせんが できません!\pくれぐれも きをつけて くださいね!$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "{JPN}またの ごりようを おまちしていますよ!$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "{JPN}レベル50と レベル100の イベント\nどちらに ちょうせん しますか?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "{JPN}では ちょうせんを はじめる まえに\nレポートを かきますが よろしいですか?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "{JPN}それでは ポケモンを\nおあずかり します!$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "{JPN}さあさあ こちらに どうぞ!$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "{JPN}おつかれさまでした!\pレンタルポケモンと\nおあずかり していた ポケモンを\lこうかん します!\pレポートを かきますので\nしょうしょう おまちください!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "{JPN}レンタルポケモンと\nおあずかり していた ポケモンを\lこうかん します!$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "{JPN}3れんしょう おめでとう ございます!\pレンタルポケモンと\nおあずかり していた ポケモンを\lこうかん します!\pレポートを かきますので\nしょうしょう おまちください!$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "{JPN}3れんしょうを きねんして\nこちらを さしあげます!$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "{JPN}おやや?\nどうぐが いっぱい ですねー\pどうぐを せいり してから\nまた きてください!$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "{JPN}おまちして おりましたよ!\pちょうせんを さいかいする まえに\nレポートを かきます!$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{JPN}おきゃくさまー!!\pぜんかい ちゃんと レポートを かいて\nしゅうりょう しませんでしたね!\pざんねんですが\nちょうせんは むこうと なります!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "{JPN}おきゃくさまの ポケモンを\nおかえしします!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{JPN}{PLAYER}は\n{STR_VAR_1}を もらった!$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}バトルトレードの ルールが かかれてる!$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの せつめいを よみますか?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}バトルトレードで つかうことの できる\nポケモンは 3ひき まで です\pレンタルするとき トレードするとき\nどちらの ときも\lおなじ しゅるいの ポケモンを\l2ひき いじょう もつことは できません$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "{JPN}トレードが できる あいては\nあなたが たたかいで\lたおした トレーナーです\pトレードで うけとる ことが できるのは\nトレーナーが つかっていた ポケモンです$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "{JPN}いちど たたかいに かつ たびに\n1かい 1ひき だけ ポケモンを\lトレード することが できます\p1かいの ちょうせんで\nトレードが できるのは\l2にんめの トレーナーまで です$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "{JPN}トレードを おこなう ときには\n2つ ちゅういする ことが あります\pその1 トレードを おこなう ときは\nあいてから うけとる ポケモンの\lつよさは かくにん できません\pその2 ちょうせんを はじめた ときに\nかりた レンタルポケモンの じゅんばんが\lトレードの あとの たたかいにも\lひきつがれます$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "{JPN}バトルテント カイナの ポケモンは\nすべて レンタルポケモン です\pレンタルポケモンの レベルは\nすべて 30に なります$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "{JPN}バトルテント シダケ かいじょうの\nルールが かかれてる!$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "{JPN}どの せつめいを よみますか?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "{JPN}バトルテント シダケかいじょう では\nポケモンたちが じぶんで\lかんがえ たたかいます\pじゅんすいな やせいの ときとは ちがって\nひとと くらしている ポケモンは\lせいかくに よって どんな こうどうを\lするかが かわるのです$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "{JPN}とにかく こうげきが\nすきな せいかく\pじぶんの みを まもることが\nすきな せいかく\pあいてを こまらせたり\nかわったことが すきな せいかく\pポケモンは せいかくに よって\nすきで とくいな わざと\lきらいで にがてな わざが ちがいます$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "{JPN}あいてに むかって じぶんから\nちょくせつ ダメージを あたえる\lこうげきの わざ\pたたかいの じゅんびや キズついた からだの\nかいふくを する ぼうぎょの わざ\pあいての のうりょくを さげたり\nどくや まひに したり など\lすこし かわった ことを する わざ\pポケモンは すべての わざを\nおおきく 3つの しゅるいに わけて\lどんな わざを だすか かんがえて います$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "{JPN}トレーナーの めいれいを うけて いない\nポケモンは うまく わざを\lだせない ことが あります\pポケモンは きらいな わざを\nつかうのは とくいでは ありません\pせいかくに あわない わざ ばかりを\nおぼえさせて いると たたかいで\lポケモンが じぶんの ちからを はっき\lできない ことが おおく なります$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "{JPN}ポケモンの せいかくの なかには\nピンチに なることで もともとの\lせいかくとは ちがう タイプの\lわざを つかう ように\lなるものが あります\pピンチに なって すこし かわった\nこうどうを はじめた ポケモンには\lじゅうぶん ちゅうい しましょう$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "{JPN}バトルテントでは\nあなたの ポケモンの レベルに あわせて\lたいせんする トレーナーの ポケモンの\lレベルが かわります\pただし レベル30より ひくい レベルの\nポケモンを つれた トレーナーが\lとうじょう することは ありません$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "{JPN}バトルテント シダケかいじょうの\nルールが かかれている!$"
