PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "{JPN}パパ『やあ {PLAYER}!\pめずらしい きのみを てに いれたから\nプレゼント するよ!$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "{JPN}ふかふかの つちに はえている きのみは\nじゆうに とっても よいのじゃが…\p1つだけ きのみを おなじ ばしょに うめる\nそれが れいぎと いうものじゃ\pほれ これを わけてやろう$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "{JPN}あんた みたところ トレーナーじゃろ?\pトレーナーは よく きのみを ポケモンに\nもたせとるわい\pふやすも つかうも あんた しだいじゃ$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "{JPN}いつも みずを あげてたら\nたくさん はなが さいたんだ\pそしたら きのみも たくさん できた!\pはい!\nこれ あげる$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "{JPN}がんばって いろんな いろの\nきのみを そだてるんだ!\l{STR_VAR_1}も がんばってね!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "{JPN}きょうは なにいろの きのみを\nさがそっかなー$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "{JPN}きのみクラッシュが だいすきだから\nきのみを あつめているんだ\pよかったら きみにも わけて あげるよ!$"

Route114_Text_TryBerryCrushWithFriends:
	.string "{JPN}きみも ともだちと\nきのみクラッシュ やってみなよ!$"

Route114_Text_FunToThinkAboutBerries:
	.string "{JPN}どの きのみを うめるか?\nきのみは つかうのか ふやすのか?\pって なやむのも また たのしいよ$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "{JPN}ひかりを いっぱい あびて\nそだつ きのみたち…\pそして きのみが げんきに そだつように\nじょうろで みずを あげる わたしたち…\pこれって あい だよね?$"

Route120_Text_YesYouUnderstand:
	.string "{JPN}うん うん!\nやっぱ わかるひとには わかるよね\pこれ あげる$"

Route120_Text_MakeYourOwnImpressions:
	.string "{JPN}そっか……\nでも ちがうと かんじることも たいせつだね\pこれ あげる$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "{JPN}その きのみは めずらしいもの らしいから\nたいせつに そだててね!$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "{JPN}また きのみめいじんに もらって こようっと$"

LilycoveCity_Text_BerrySuitsYou:
	.string "{JPN}やっぱり\pわたしに スーツが にあうように\nうみには しおかぜが にあうな\lそして きみには きのみが にあいそうだ……\pなんでだろうね?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "{JPN}やっぱり それは…………\pきみが トレーナーだからだ!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "{JPN}やっぱり\pわたしに シンプルさが にあうように\nポケモンには ポロックが にあうな$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "{JPN}わしは きのみめいじんと よばれておる\pわしは せかいじゅうを うつくしい はなで\nうめつくそうと きのみを そだてて\lそして くばり まくって おるのじゃ\pきみにも きのみを わけて あげよう!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "{JPN}ほれ えんりょ せずに もう ひとつ!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "{JPN}カナズミの ちかくにある サン・トウカという\nフラワーショップも よろしくの\pせかいに はなを さかせましょう!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "{JPN}きょうは もう おしまいじゃ\nまた おいで\pせかいに はなを さかせましょう!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "{JPN}じいさんの きのみの そだてかたは\nそりゃあ せかいいちじゃ\pわしも はなが たかいわい\pところで あんた\nいい ことばを きいたことが ないかい?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "{JPN}おお! とても よい ことばじゃ!\nかんどう したわい\pほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "{JPN}おお! なかなか よい ことばじゃ\nあんたも たいしたもんじゃ\pほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "{JPN}まごたち 4にんも じいさんを しのぐ\nおおものに なるじゃろうて\pじんせい たのしいことが つきんのう!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "{JPN}ほう……$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "{JPN}こんにちは!\pはなを せかいに ひろめる\nフラワーショップ サン・トウカです!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{JPN}{PLAYER}{KUN} きのみの こと しりたい?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "{JPN}あなたの なまえは……\p{PLAYER}{KUN}ね!\nとっても いい なまえだね!\l{PLAYER}{KUN} きのみのこと しりたい?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "{JPN}きのみはね くろい ふかふかの つちの\nところで たまに とれるの\lでね……\pとったら その1つを また うめるの!\pそうすると その きのみ から\nめがでて みきが できて はながさいて\lまた きのみ が できるの\pそうやって はなを ふやして\nせかいじゅうを はなに するのが\lわたしの ゆめ なんだ!\pだから {PLAYER}{KUN}も きのみを うめて\nせかいに はなを ふやしてね!$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "{JPN}おはなって とっても しあわせな きぶんに\nしてくれるよね$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "{JPN}こんにちは!\pおはなは せわを すれば するほど\nたくさん きれいに さいて くれるの\pあなたも せわを したく なった でしょ?\nこれ あげるわ$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "{JPN}きのみが そだつ たびに\nじょうろで みずを あげてね!\pあとね\pきのみは ずっと ずっと ほうっておくと\nじめんに おちてしまうの\lでもね そこから また めがでて くるの!\pすごいよね!\nいきものの ちからを かんじるよね$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "{JPN}おねーちゃんたちを みならって\nがんばって おはなを そだててるの\pはい! これあげる!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "{JPN}きのみは うめて おおきく したり\nポケモンに もたせたり できるの\pでも さいきん きのみを いくつか まぜると\nポケモンの おかしになる きかいが\lある らしいんだ\pあたしも おかし ほしー$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "{JPN}{STR_VAR_1} なまえ なんていうの?\p……… ……… ………\nへー いいねー\pわたしは キリ っていう なまえなの\pパパと ママが すくすくと そだって\nこころの あたたかい おんなのこに なって\lほしいっていう ねがいを こめたんだって!\p{STR_VAR_1}にも これ あげる$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "{JPN}あと {STR_VAR_1}には キリの だいすきな\nこの きのみも あげちゃう!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "{JPN}{STR_VAR_1}の なまえには\nどんな ねがいが こめられてるの?$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "{JPN}はる なつ あき ふゆ\nはるに うまれると はるが すきで\lなつに うまれると なつが すきなのかな?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "{JPN}じゃあ キリは あきに うまれたから\nあきが だいすき!\p{STR_VAR_1}は いつが すき?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "{JPN}そっか…\nかんけいないのか…\pしりたいことって たくさんあるなー$"
