gText_Birch_Welcome::
	.string "{JPN}いやー おまたせ おまたせ!\pポケットモンスターの せかいへ\nようこそ!\pわたしの なまえは オダマキ!\pでも みんな からは\n「ポケモンはかせ」と よばれて いるよ!\p"

gText_Birch_Pokemon::
	.string "{JPN}ポケットモンスター\n……すなわち ポケモン{PAUSE 96}$"

gText_Birch_MainSpeech::
	.string "{JPN}この せかいには\nポケモンと よばれる いきもの たちが\lいたるところに すんでいる!\pわれわれ にんげんは\nポケモンと なかよく あそんだり\lたすけあって しごとを したり\pときには ちからを あわせて\nたたかったり しながら\pいっしょに くらして いるんだ!\p……しかし われわれは ポケモンの\nすべてを しっている わけでは ない\pポケモンの ひみつは\nまだまだ いっぱい ある!\pその ひみつを ときあかす ため\nわたしは けんきゅうを つづけている\lという わけなんだ!\p$"

gText_Birch_AndYouAre::
	.string "{JPN}ところで きみは……?$"

gText_Birch_BoyOrGirl::
	.string "{JPN}おとこのこ?\nそれとも おんなのこ?$"

gText_Birch_WhatsYourName::
	.string "{JPN}なまえも おしえて くれるかい!$"

gText_Birch_SoItsPlayer::
	.string "{JPN}{PLAYER}{KUN} だね?$"

gText_Birch_YourePlayer::
	.string "{JPN}……そうか!\pきみが こんど わたしの すむ まち\nミシロタウンに ひっこして くる\l{PLAYER}{KUN} だったのか!\p$"

gText_Birch_AreYouReady::
	.string "{JPN}よーし じゅんびは いいかい?\pこれから きみ だけの ものがたりが\nはじまろうと している!\pゆめと ぼうけんと であいに みちた\nポケットモンスターの せかいへ\lゆうきを もって とびこんで みてくれ!\pでは また あとで あおう!\nけんきゅうじょで まって いるぞ!\p$"
