BerryBlender_Text_BlendWithTheBlendMaster:
	.string "{JPN}めいじん『いかにも!\nわしが ブレンドめいじん じゃ!\pいっしょに まわして\nわしの すごい わざを みるがよい$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "{JPN}めいじん『ふむむむっ! おぬし\nわしの すごい わざを みたいのじゃな?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "{JPN}ふむむむっ!\pいまは いそがしいのじゃな!\pあんしん するのじゃ!\nわしは きょう ずっと ここに おる\lようが すんだら すぐに くるのじゃぞ!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "{JPN}ふむむむっ!\pおぬし きのみを もっておらんぞ!\pわしは きょう ずっと ここに おるから\nはやく きのみを みつけて くるのじゃぞ!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "{JPN}そうじゃろう!\nそうじゃろう!\pとろころで おぬし……\nむろん ポロックの つくりかたは\lしっておる じゃろうな?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "{JPN}ふむむむっ!\pまあ かんたんな ことじゃ!\pきのみ ブレンダーの マークが\nじぶんの ところに きたら\lボタンを おせば いいだけじゃ!\pわしの かんぺきな おしかたを みれば\nすぐに わかるはずじゃ!$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "{JPN}よしっ!\pでは はじめるぞ!\pめいじんと いっしょに\nレッツ きのみブレンダー!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "{JPN}ふむむむっ!\pおぬし ポロックケースを\nまだ もっておらん ようじゃぞ!\pわしは きょう ずっと ここに おるから\nポロックケースを もらってから\lまた くるのじゃ!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "{JPN}ふむむむっ!\pおぬし ポロックケースが\nいっぱいの ようじゃぞ!\pわしは きょう ずっと ここに おるから\nポロックを へらしてから\lまた くるのじゃ!$"

BerryBlender_Text_WhoaAwesome:
	.string "{JPN}すげぇー!$"

BerryBlender_Text_WickedlyFast:
	.string "{JPN}はぇー!$"

BerryBlender_Text_WhatAnExpert:
	.string "{JPN}うめぇー!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "{JPN}めいじんと いっしょに やったら\nとっても すごい ポロック できたの$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "{JPN}やじるしを おっていく\nスキのない めの うごき!\pボタンを おすときの\nせいかくな ての うごき!\pこの ふたつを あわせもつ\nめいじんは ホント すごいね!$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "{JPN}めいじんは どこかの やまおくで\nしゅぎょう しているらしいの\pそして ときどき\nミナモシティに やってきて\lきのみブレンダーを 1にちじゅう\lするらしいわ$"
