@ 注: このファイルの brailleformat マクロは、RS からの残り物です。
@       その番号は単にスキップされます。
@       このマクロを使用しないようにする場合は、`ScrCmd_braillemessage` を編集して、
@       このセクションがスキップされないようにする必要があります。
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "ここで あがれ$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "あいうえお$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "さしすせそ$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "なにぬねの$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "まみむめも$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "かきくけこ$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "たちつてと$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "はひふへほ$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "や ゆ よ$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "らりるれろ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille "わ を ん$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "ここで\nあなをほる$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "さいしょに ほえるおー\n"
	.braille "さいごに じーらんす\n"
	.braille "そして すべてが\n"
	.braille "ひらかれる$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "わたしたちわ\n"
	.braille "この あなで\n"
	.braille "くらし せいかつ し\n"
	.braille "そして いきて きた$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "すべてわ\n"
	.braille "ぽけもんの\n"
	.braille "おかげだ$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "だが\n"
	.braille "わたしたちわ\n"
	.braille "あの ぽけもんを\n"
	.braille "とじこめた$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "こわかったのだ$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "ゆーき ある\n"
	.braille "ものよ\n"
	.braille "きぼーに\n"
	.braille "みちた ものよ$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "とびらを あけよ\n"
	.braille "そこに えいえんの\n"
	.braille "ぽけもんが いる$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "ひだり ひだり\n"
	.braille "した した\n"
	.braille "そこで\n"
	.braille "いわくだきを つかえ$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "かべから\n"
	.braille "はなれず\n"
	.braille "ここを\n"
	.braille "ひとまわりせよ$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "われわれの いしを\n"
	.braille "つぎし ものよ\n"
	.braille "まんなかで\n"
	.braille "ひかりかがやけ$"

@ FRLG
Braille_Text_Up::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "うえ$"

Braille_Text_Down::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "した$"

Braille_Text_Right::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "みぎ$"

Braille_Text_Left::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ひだり$"

Braille_Text_Cut::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "いあいぎり$"

Braille_Text_ABC::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "あいうえお$"

Braille_Text_GHI::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "さしすせそ$"

Braille_Text_MNO::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "なにぬねの$"

Braille_Text_TUV::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "まみむめも$"

Braille_Text_DEF::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "かきくけこ$"

Braille_Text_JKL::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "たちつてと$"

Braille_Text_PQRS::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "はひふへほ$"

Braille_Text_WXYZ::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "らりるれろ$"

Braille_Text_Period::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "や ゆ よ$"

Braille_Text_Comma::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "わ を ん$"

Braille_Text_Everything::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ものごと にわ$"

Braille_Text_HasMeaning1::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "いみが ある$"

Braille_Text_Existence::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "そんざい にわ$"

Braille_Text_HasMeaning2::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "いみが ある$"

Braille_Text_BeingAlive::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "いきる ことにわ$"

Braille_Text_HasMeaning3::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "いみが ある$"

Braille_Text_HaveDreams::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ゆめを もて$"

Braille_Text_UsePower::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ちからを つかえ$"

Braille_Text_LetTheTwo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ひかり かがやく$"

Braille_Text_Glittering::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ふたつの いし$"

Braille_Text_Stones::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ひとつわ あかく$"

Braille_Text_OneInRed::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ひとつは あおく$"

Braille_Text_OneInBlue::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ふたつの ちからで$"

Braille_Text_ConnectThe::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "かこが つながり$"

Braille_Text_Past::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ひかり かがやく$"

Braille_Text_TwoFriends::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "そして$"

Braille_Text_Sharing::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "あたらしい せかいが$"

Braille_Text_PowerOpen::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "みえてくる$"

Braille_Text_AWindowTo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "つぎの せかいを$"

Braille_Text_ANewWorld::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "つくるのわ あなただ$"

Braille_Text_ThatGlows::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "もー はじまっている$"

Braille_Text_TheNext::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THE NEXT$"

Braille_Text_WorldWaits::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "WORLD WAITS$"

Braille_Text_ForYou::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "FOR YOU.$"

