Text_PictureBookShelf:
	.string "{JPN}ポケモンえほんが そろってる!$"

Text_BookShelf:
	.string "{JPN}いろんな ほんが いっぱいだ!$"

Text_PokemonCenterBookShelf:
	.string "{JPN}ポケモンざっしが ならんでる!\p……「ポケモンのとも」\n……「ポケモン てちょう」\l……「かわいい ポケモン」$"

Text_Vase:
	.string "{JPN}たかそうな つぼが ある!\nのぞきこむと……\pなかは からっぽ だ!$"

Text_EmptyTrashCan:
	.string "{JPN}なかは からっぽ だ!$"

Text_ShopShelf:
	.string "{JPN}たくさんの ポケモン グッズが\nところせましと ならべられてる!$"

Text_Blueprint:
	.string "{JPN}なにかの せっけいず……?\nみても チンプンカンプン!$"
