EventTicket_Text_ShowOldSeaMap:
	.string "{JPN}カイナいき れんらくせん……\pえ? この ちずの とおりに\nいってくれって?\pわたしでは よく わからないので\nおまちください$"

EventTicket_Text_ThatPass:
	.string "{JPN}カイナいき れんらくせん……\pあら?\nその チケットは……!$"

EventTicket_Text_ShowEonTicket:
	.string "{JPN}ヘンテコな チケットを\nもってきたのは おまえさんか?\pおまえが いこうと しているのは\nみなみの はての ちっぽけな しま……\pそこでは なにが おこるのか\nだれも わからねえ……\lううむ ふなのりの ちが さわぐぜ!\pさあ のりな!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "{JPN}なにもねえ ちんけな しま だな……\nミナモへ かえるか?$"

EventTicket_Text_SailHome:
	.string "{JPN}よし! かえると するか!$"

EventTicket_Text_AsYouLike:
	.string "{JPN}そうかい\nまあ すきにするが いいさ$"

SouthernIsland_Interior_Text_Sign:
	.string "{JPN}すべての ゆめは もうひとつの げんじつ\nそれを わすれるべからず……$"

SouthernIsland_Exterior_Text_Sign:
	.string "{JPN}きおく かすみし ものは\nこころに きざみつける ことを のぞむ……$"
