EventTicket_Text_OldSeaMapTooFar:
	.string "{JPN}なんだ?\nボロっちい ちずを もってきたってのは\lおまえさんか? みせてみな!\p…… …… ……\pこりゃ また ずいぶん とおいなあ\nわりいが ほかを あたったほうが……$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "{JPN}ハギ『こら! わしの おんじんの\nねがいを ことわるとは なにごとだ!$"

EventTicket_Text_BrineyLetsSail:
	.string "{JPN}{PLAYER}{KUN} すまなかったね\nこのふねを たよって きて くれたのに……\lもちろん いますぐに しゅっこうだ!\pさあいくぞ!\nかいずに ある しまへ しゅっぱつ!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "{JPN}みょうな チケットを\nもってきたのは おまえさんか?\pおまえが いこうと しているのは\nとおく はなれた ちほうの しま……\lそこには なにが まっているのか\lしって いるやつは いねえ……\lううむ ふなのりの ちが さわぐぜ!\pさあ のりな!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "{JPN}まったく ハギ せんちょうの\nきまぐれにも まいるよなあ……\pもう ミナモへ かえるのかい?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "{JPN}ふしぎな かたちの しまだなあ\nもう ミナモへ かえるか?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "{JPN}ヘンテコな チケットを\nいくつも もってきたのは おまえさんか?\p…… …… ……ふむ\pこいつらで いける ところは\nどこも ここから とおい しま\lそこでは なにが おきるのか\lなにが まっているのか\lしっている やつは いねえ……\lううむ ふなのりの ちが さわぐぜ!\pさあ のりな!\nまずは どこから いってみるかい?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "{JPN}な…… なんか おくふかくから\nひくい うなりが きこえたような……\pだ だいじょうぶか?\nもう かえった ほうが いいんじゃないか?$"

FarawayIsland_Entrance_Text_Sign:
	.string "{JPN}なんねんも まえに かかれたような\nふるい かきおきが ある……\p……がつ 6か\nここに たちいる にんげ……が\lふたたび ……らわれると すれば\lこころ やさし……で あらんことを\p……こに その ねがいを しるし\nこの ……を あとにする\p……ジ$"

FarawayIsland_Interior_Text_Mew:
	.string "{JPN}ミュー……$"
