LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "{JPN}こちらは ポケモンくじ\nちゅうせん コーナーです\pとうデパートに おこし いただいた かたに\nもれなく ポケモンくじを\lひいて いただいて います!\pひいた くじの ナンバーと\nおきゃくさまの ポケモンの IDが\lあっていましたら すてきな しょうひんを\lプレゼント いたします!\pポケモンくじを ひかれますか?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "{JPN}また あした いこう\nおこし ください$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "{JPN}それでは また おこし ください$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "{JPN}では くじを ひいて ください\n…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "{JPN}くじの ナンバーは {STR_VAR_1}です!\pナンバーが あなたの ポケモンの IDと\nいっちしているか おしらべ いたしますので\lしょうしょう おまちください$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "{JPN}おめでとう ございます!\pあなたが つれている\n{STR_VAR_1}ちゃんの IDが みごとに\lくじの ナンバーと いっち しました!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "{JPN}おめでとう ございます!\pパソコンに あずけている\n{STR_VAR_1}ちゃんの IDが みごとに\lくじの ナンバーと いっち しました!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "{JPN}ざんねんでした\nすべて はずれの ようです$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "{JPN}2ケタ あって いましたので\n3とう です!\l{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "{JPN}3ケタ あって いましたので\n2とう です!\l{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "{JPN}4ケタ あって いましたので\n1とう です!\l{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "{JPN}なんと 5ケタ すべて\nあって いました!!\pとくとうです!!\n{STR_VAR_1}を さしあげます!!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "{JPN}………あら?\nどうぐが いっぱいの ようですね\pどうぐを せいりしてから もういちど\nおこし ください.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{JPN}{PLAYER}さん ですね\nおまちして おりました!\pでは しょうひんを\nおわたし いたします$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "{JPN}それでは また おこし ください$"
