@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "{JPN} きれい だよねー$"

GiddyText_SoDarling::
	.string "{JPN} かわいい よねー$"

GiddyText_SoRelaxed::
	.string "{JPN} のんびり だよねー$"

GiddyText_SoSunny::
	.string "{JPN} ぽっかぽか だよねー$"

GiddyText_SoDesirable::
	.string "{JPN} あこがれる よねー$"

GiddyText_SoExciting::
	.string "{JPN} ドキドキ するよねー$"

GiddyText_SoAmusing::
	.string "{JPN} おもしろい よねー$"

GiddyText_SoMagical::
	.string "{JPN} ふしぎ だよねー$"

GiddyText_Is::
	.string "{JPN}って$"

GiddyText_DontYouAgree::
	.string "\n{JPN}\nそう おもわない?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "{JPN}たびに でたいなー\nどこか いい ところ しらない?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "{JPN}120しょくの クレヨン かったんだー\nいいでしょう?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "{JPN}しゃぼんだまに のって とべるように\nならないかなー$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "{JPN}すなはまに かいた もじは\nすぐに きえちゃうのが かなしいよねー$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "{JPN}うみの そこって どうなってるのかなー\nいちどで いいから みて みたいなー$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "{JPN}ゆうやけを みると\nウチに かえりたく ならない?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "{JPN}みどりの しばで ねころがると\nきもちいいよねー$"

GiddyText_SecretBasesAreSoWonderful::
	.string "{JPN}ひみつきち って いいよね!\nなんか わくわく してこない?$"
