MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "{JPN}この わざを おしえて もらえるのは\nいちど だけですが いいですか?$"

MoveTutor_Text_SwaggerTeach:
	.string "{JPN}ふふーん\nおれの ポケモンは すごいのさ!\lどの ポケモンよりも かっこいいのさ!\p……って いばってたら\nもう いばらない ことに したから\nかわりに おまえの ポケモンに\lいばる わざを おしえて やってもいいぜ$"

MoveTutor_Text_SwaggerDeclined:
	.string "{JPN}えー\nなんだよ つきあい わるいな$"

MoveTutor_Text_SwaggerWhichMon:
	.string "{JPN}おう!\nどの ポケモンが いばりたいんだ?$"

MoveTutor_Text_SwaggerTaught:
	.string "{JPN}こんどっから いばる かわりに\nじまん するだけに しておくよ……$"

MoveTutor_Text_RolloutTeach:
	.string "{JPN}ねえ ここから あっちに むかって\nいちども まがらずに ずーっと\lあるいて いけるって しってた?\lぼく なら ころがって いけるかも……!\pきみの ポケモンも ころがって みる?\nころがる なら おしえて あげられるよ$"

MoveTutor_Text_RolloutDeclined:
	.string "{JPN}えんりょ いらないのに!\nごろ ごろ$"

MoveTutor_Text_RolloutWhichMon:
	.string "{JPN}えへへ いいよ!\nぼく そっくりの ポケモンだと いいな$"

MoveTutor_Text_RolloutTaught:
	.string "{JPN}くさに ねころがると しあわせだなー\nごろ ごろ$"

MoveTutor_Text_FuryCutterTeach:
	.string "{JPN}おなじ わざをさ\nつづけて なんども だすと\lどんどん つよくなる わざが あるの!\lしかも むしタイプで かっこいいの!\pれんぞくぎりって いうんだけど\nおぼえて みたい?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "{JPN}きが あわないねぇ$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "{JPN}わーい!\nじゃ おぼえさせる ポケモンを おしえてね$"

MoveTutor_Text_FuryCutterTaught:
	.string "{JPN}れんぞくして あたるか どうかの\nスリルが たのしいんだよねぇ$"

MoveTutor_MimicTeach:
	.string "{JPN}おお おわかいの!\nわしは こども じゃが\lこのまちの じいちゃんや ばあちゃんの\lはなしかたを ものまね しておるのじゃ!\pどうかね? おわかいの\nおぬしの ポケモンに わしが\lものまねを おしえて やろうかね?$"

MoveTutor_MimicDeclined:
	.string "{JPN}ちぇっ なーんだ!\nボク ものまね おしえたいのにな!$"

MoveTutor_Text_MimicWhichMon:
	.string "{JPN}ふぉっ ふぉっ! よかろう!\nおしえさせる ポケモンを みせてみぃ$"

MoveTutor_Text_MimicTaught:
	.string "{JPN}ものまねは おくの ふかい わざじゃ!\nボ… わしの ように\lうまく できるかな?$"

MoveTutor_Text_MetronomeTeach:
	.string "{JPN}あーん ほしいものが いっぱい!\nでも おこづかいは なくなっちゃったし……\pゆびを ふれば まほうで\nおこづかい でてくれば いーのにな!\lなんてね エヘヘ……\pしかたが ないから\nあなたの ポケモンに\lゆびをふる でも おしえて あげよっか?$"

MoveTutor_Text_MetronomeDeclined:
	.string "{JPN}そっか\nきが むいたら またおいでよ!$"

MoveTutor_Text_MetronomeWhichMon:
	.string "{JPN}うん! じゃ おしえるね\nどのコが いいのかな?$"

MoveTutor_Text_MetronomeTaught:
	.string "{JPN}ゆびをふると ステキな ことが\nいっぱい おきるんだよー!\pわたしたちも つかえたら いーのにね!$"

MoveTutor_Text_SleepTalkTeach:
	.string "{JPN}ふん…… ばあさんめ\nめざめるパワー などに\lたより おって……\pワシと いっしょに おひるね して\nねごとでも いってたほうが たのしいのに\pもう あんたの ポケモンでも ええわ\nねごとを おぼえて つかってみんか?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "{JPN}そうかい そうかい……\nみんな めざめるパワーが だいすきかい$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "{JPN}むぉう! ものわかりの いい こどもよ!\nさて ポケモンは どいつが いいかな?$"

MoveTutor_Text_SleepTalkTaught:
	.string "{JPN}ワシ ばあさんの コイン\nいちども あてたことが なくてな……\lねごとでも ええから あたらんかな$"

MoveTutor_Text_SubstituteTeach:
	.string "{JPN}ふう\nこうやって おくじょうから\lひろい せかいを みていると……\pなんにんもの じぶんが いて\nいくつもの じんせいを たのしめたらなー\lって おもうの!\lムリな はなしだけどね うふふ\pそうだわ あなたの ポケモンちゃん!\nみがわりの わざ おぼえてみない?$"

MoveTutor_Text_SubstituteDeclined:
	.string "{JPN}あら そう?\nポケモンなら じぶんの ぶんしんを\lつくる ことが できるのに$"

MoveTutor_Text_SubstituteWhichMon:
	.string "{JPN}うふふ\nどの ポケモンちゃんが いいかしら?$"

MoveTutor_Text_SubstituteTaught:
	.string "{JPN}わたしたち にんげんは\nじぶんの じんせいを\lおもいきり たのしまなきゃ ね!\lあなたも そうなるように いのってる!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "{JPN}もう できんわ!\pぜったい ムリだわ!\pかくとうタイプの オレは\nトクサネの ジムでは\lぜんぜん かてんわ!\pちきしょーっ! ボカ ボカ!\nボカ ボカ! ボカ ボカ!\pなんだよ\nじめんを なぐってる だけだろ!\pそれとも おまえの ポケモンに\nばくれつパンチを おしえて ほしいのかよ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "{JPN}ちきしょー おまえまで\nオレを ばかに するかっ!?\lボカ ボカ!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "{JPN}うぉー! ほんとか! いいやつだな!\nどのポケモンに おしえれば いい?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "{JPN}なあ ばくれつパンチ つかって\nトクサネジムで かって きてくれよ!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "{JPN}あーあ\nルネシティの ジムリーダーって\lすっごく すてきだから\lライバルが いっぱい なのよねー\pこの あたしが すてみで ぶつかっても\nダメだったわ!\pねえ あなた!\nじきでんの すてみタックル!\lあなたの ポケモンに おしえさせてよ!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "{JPN}うん もう!\nあなたに まで ふられちゃったわ$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "{JPN}ん じゃあ\nどの ポケモンが いいか きめてよ$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "{JPN}もう いいわっ!\nあたしも こいを すてて\lつよい オンナに なってやるっ!$"

MoveTutor_Text_ExplosionTeach:
	.string "{JPN}ぼかぁ こんな イナカで\nいつまでも くすぶっとる つもりは\lまったく ないんじゃあー!\pみとれよ いつか トカイに でて\nドッカーンと はでに やって やるわい!\pおいっ! おまえ きいとったん なら\nけいきよく だいばくはつを おしえさせろ!$"

MoveTutor_Text_ExplosionDeclined:
	.string "{JPN}がーっ!\nイナカもん だからって ことわるなあ!$"

MoveTutor_Text_ExplosionWhichMon:
	.string "{JPN}ぃよーし ドッカーンと おぼえさせるか!\nどの ポケモンが ぶちかますんか?$"

MoveTutor_Text_ExplosionTaught:
	.string "{JPN}いつも ポケモンに ばっか\nだいばくはつを おしえとって\lかんじんの ぼくは いつまでも\lばくはつ できん……\pでも ほんとは\nこのまちに いつまでも いたいから\lかも しれん……$"
