MoveRelearner_Text_WouldLearnNewMoves:
	.string "{JPN}こちらは わざマニアです\n"
	.string "{JPN}わざを おもいださせますか?$"

MoveRelearner_Text_LevelUpMoves:
	.string "{JPN}レベルアップわざ$"

MoveRelearner_Text_EggMoves:
	.string "{JPN}タマゴわざ$"

MoveRelearner_Text_TMMoves:
	.string "{JPN}わざマシンわざ$"

MoveRelearner_Text_TutormoveMoves:
	.string "{JPN}おしえわざ$"

MoveRelearner_Text_SeeYa:
	.string "{JPN}やめる$"

MoveRelearner_Text_AnythingElse:
	.string "{JPN}ほかに ごようけんは?$"

MoveRelearner_Text_ChoosePkmn:
	.string "{JPN}おもいださせる ポケモンを えらんでください$"

MoveRelearner_Text_HaveNoPkmn:
	.string "{JPN}ポケモンを もっていません!$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "{JPN}もうしわけありません……\nタマゴには わざは おしえられません$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "{JPN}もうしわけありません……\pその ポケモンに\nおしえられる わざは ありません$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "{JPN}レベルアップわざ$"

MoveRelearner_Text_EggMoveLWR::
	.string "{JPN}タマゴわざ$"

MoveRelearner_Text_TMMoveLWR::
	.string "{JPN}わざマシンわざ$"

MoveRelearner_Text_TutorMoveLWR::
	.string "{JPN}おしえわざ$"

MoveRelearner_Text_MoveLWR::
	.string "{JPN}わざ$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "{JPN}どのポケモンに {STR_VAR_3}を おしえますか?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "{JPN}ごりよう ありがとうございます!\nまた おまちしております!$"
