gText_ObtainedTheItem::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_TheBagIsFull::
	.string "{JPN}バッグが いっぱいだ!$"

gText_PutItemInPocket::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n{STR_VAR_3}ポケットに しまった!$"

gText_PlayerFoundOneItem::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\nみつけた!$"

gText_TooBadBagIsFull::
	.string "{JPN}ざんねん!\nバッグが いっぱいだ……$"

gText_PlayerPutItemInBag::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\nバッグに しまった!$"

gText_ObtainedTheDecor::
	.string "{JPN}{STR_VAR_2}を てにいれた!$"

gText_NoRoomLeftForAnother::
	.string "{JPN}ざんねん! {STR_VAR_2}を\nいれる ばしょが いっぱいだ……$"

gText_TheDecorWasTransferredToThePC::
	.string "{JPN}{STR_VAR_2}は\nパソコンに てんそうされた!$"

gText_ObtainedTheItems::
	.string "{JPN}{STR_VAR_1}と {STR_VAR_2}を てにいれた!$"

gText_PlayerFoundItems::
	.string "{JPN}{PLAYER}は {STR_VAR_1}と {STR_VAR_2}を みつけた!$"

gText_PutCoinsAwayInCoinCase::
	.string "{JPN}{PLAYER}は \nコインケースに しまった!$"

gText_FoundXCoins::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n{STR_VAR_1}まい みつけた!$"

gText_FoundXItems::
	.string "{JPN}{PLAYER}は {STR_VAR_2}を\n{STR_VAR_1}こ みつけた$"

gText_CoinCaseIsFull::
	.string "{JPN}ざんねん!\nコインケースが いっぱいだ……$"

gText_NothingToPutThemIn::
	.string "{JPN}ざんねん!\nいれるものが ない……$"
