Text_BootUpPC:
	.string "{JPN}{PLAYER}は\nパソコンの スイッチを いれた$"

gText_WhichPCShouldBeAccessed::
	.string "{JPN}どこの パソコンに せつぞく して\nつうしん しますか?$"

gText_AccessedSomeonesPC::
	.string "{JPN}だれかの パソコンに せつぞく した!$"

gText_StorageSystemOpened::
	.string "{JPN}ポケモンの あずかり システムを\nよびだした!$"

gText_AccessedPlayersPC::
	.string "{JPN}{PLAYER}の パソコンに せつぞくした!$"

gText_AccessedLanettesPC::
	.string "{JPN}マユミの パソコンに せつぞく した!$"

gText_AccessedBillsPC::
	.string "{JPN}マサキの パソコンに せつぞく した!$"
