gText_PkmnTransferredSomeonesPC::
	.string "{JPN}{STR_VAR_2}は だれかのパソコンの\nボックス『{STR_VAR_1}』に\lてんそう された!$"

gText_PkmnTransferredLanettesPC::
#if IS_FRLG
	.string "{JPN}{STR_VAR_2}は マサキのパソコンの\n"
#else
	.string "{JPN}{STR_VAR_2}は マユミのパソコンの\n"
#endif
	.string "ボックス『{STR_VAR_1}』に\lてんそう された!$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{JPN}だれかのパソコンの\nボックス『{STR_VAR_3}』が\lいっぱいだ!!\p{STR_VAR_2}は\nボックス『{STR_VAR_1}』に\lてんそう された!$"

gText_PkmnTransferredLanettesPCBoxFull::
#if IS_FRLG
	.string "{JPN}マサキのパソコンの\n"
#else
	.string "{JPN}マユミのパソコンの\n"
#endif
	.string "ボックス『{STR_VAR_3}』が\nいっぱいだ!!{STR_VAR_2}は\nボックス『{STR_VAR_1}』に\lてんそう された!$"

gText_PkmnSentToPCAfterCatch::
	.string "{JPN}{STR_VAR_2}は {B_PC_CREATOR_NAME}のパソコンの\nボックス『{STR_VAR_1}』に\lてんそう された!$"

gText_PlayerObtainedTheMon::
	.string "{JPN}{PLAYER}は {STR_VAR_1}を\nてにいれた!$"

gText_NoMoreRoomForPokemon::
	.string "{JPN}ポケモンを もちきれません!\pボックスも いっぱいで\nてんそう できません$"

gText_NicknameThisPokemon::
	.string "{JPN}{STR_VAR_1}に\nニックネームを つけますか?$"
