gText_WouldYouLikeToRestYourPkmn::
	.string "{JPN}おつかれさまです!\nポケモン センター です\pここでは ポケモンの\nたいりょく かいふくを します\pあなたの ポケモンを\nやすませて あげますか?$"

gText_IllTakeYourPkmn::
	.string "{JPN}それでは\nおあずかり いたします!$"

gText_RestoredPkmnToFullHealth::
	.string "{JPN}おまちどおさま!\pおあずかり した ポケモンは\nみんな げんきに なりましたよ!$"

gText_WeHopeToSeeYouAgain::
	.string "{JPN}またの\nごりようを おまち してます!$"

gText_WelcomeCutShort::
	.string "{JPN}おつかれさまです!\nポケモン センター です\pここでは ポケモンの\nたいりょく かいふくを します\pあなたの ポケモンを……$"

gText_NoticesGoldCard::
	.string "{JPN}そ それは……\nひょっとして ゴールドカード!?\pああ…… きんいろが まぶしい!\n4つの ほしが かがやかしい!\pわたしも これまでに\nシルバーカードの トレーナーさんなら\lなんにんか みてきましたが\lゴールドカードを おもちの かたは\l{PLAYER}さんが はじめて ですよ!\pさあ {PLAYER}さんの\nポケモンを やすませて あげましょう!$"

gText_YouWantTheUsual::
	.string "{JPN}{PLAYER}さん おつかれさまです!\nいつもので よろしい ですね!$"

gText_IllTakeYourPkmn2::
	.string "{JPN}では おあずかりさせて いただきます!$"

gText_ThankYouForWaiting::
	.string "{JPN}たいへん おまたせ いたしました!$"

gText_WeHopeToSeeYouAgain2::
	.string "{JPN}また いつでも おこしください!$"
