Questionnaire_Text_FillOut::
	.string "{JPN}アンケートようの メモようしが ある\nアンケートに なにか かきますか?$"

Questionnaire_Text_ThankYou::
	.string "{JPN}アンケートに ごきょうりょく\nいただき ありがとう ございます!\pこの アンケートは こんごの\nさんこうに させて いただきます!$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "{JPN}…… おきゃくさま!\nそのことばを しってるの ですか!\pということは ふしぎなおくりもの を\nしって いらっしゃるの ですね!\pこれからは あなたにも\nふしぎなおくりもの が\lとどくように なるでしょう!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "{JPN}レポートをかくと ふしぎなおくりもの が\nつかえるように なります$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "{JPN}…… おきゃくさま!\nそのことばを しってるの ですか!\pということは ふしぎなできごと を\nしって いらっしゃるの ですね!$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "{JPN}レポートをかくと ふしぎなできごと が\nつかえるように なります$"

MysteryGift_Text_TheresATicketForYou::
	.string "{JPN}ふしぎなできごと を ごりよう\n{JPN}いただき ありがとう ございます!\l{PLAYER}さま ですね\pあなたさま あてに\nこの チケットが\lおくられて きました$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "{JPN}ミナモシティの ふなつきば で\nつかえる ようですね\pぜひ ごりよう してみては\nいかがでしょうか?$"
