	.align 2
gText_ConfirmSave::
	.string "{JPN}ここまでの かつやくを\nポケモンレポートに かきこみますか?$"

gText_AlreadySavedFile::
	.string "{JPN}まえに かかれた レポートに\nうえから かいても いいですか?$"

gText_SavingDontTurnOff::
	.string "{JPN}ポケモンレポートに かきこんでいます\nでんげんを きらないで ください$"

gText_PlayerSavedGame::
	.string "{JPN}{PLAYER} は\nレポートに しっかり かきのこした$"

gText_DifferentSaveFile::
	.string "{JPN}ちゅうい!!\p『つづきから はじめる』で\nぼうけん していた レポートが\lかかれています!\pそちらで プレイしていた ぼうけんや\nすべての ポケモン どうぐ などが\lきえてしまいます……\pほんとうに\nうえから かいても いいですか?$"

gText_SaveError::
	.string "{JPN}レポートが かけませんでした\pバックアップカートリッジを\nこうかんしてください!$"

gText_SavingDontTurnOffPower::
	.string "{JPN}ポケモンレポートに かきこんでいます\nでんげんを きらないで ください$"
