ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "{JPN}このさきに すすむのかね?\pもし よかったら\nあさせのしおと あさせのかいがらを\lあつめてきて くれないか\pざいりょうが あつまったら\nわたしが いいもの つくるんだがね$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "{JPN}あさせのしおと あさせのかいがら\nそれぞれ 4つ あれば\lかいがらのすずが つくれるんだが……\pかいがらのすずの ざいりょう なら\nまいにち とれるよ$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "{JPN}お! あさせのしおと あさせのかいがら!\nりょうも じゅうぶんだ!\pこれで かいがらのすず\nつくっても いいかね?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "{JPN}かいがらのすず\nさっそく つくらせて もらうよ\p…… …… ……\n…… …… ……\pよし できたっ!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "{JPN}ポケモンに もたせてあげると よろこぶよ\pなんたって かいがらのすずの ねいろは\nてんか いっぴん だからね\pかいがらのすずの ざいりょう なら\nまいにち とれるから\lそろえば また つくらせて もらうよ$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "{JPN}そうかね……\nかいがらのすず つくりたかった……$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "{JPN}つくっても バッグが いっぱいで\nもてない ようだね……\pせいりして また くると いいよ$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "{JPN}あさせのしおを とった あと……\nいまは なにも ない……$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "{JPN}あさせのかいがらを みつけた あと……\nいまは なにも ない……$"
