#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("くん");
const u8 gText_ExpandedPlaceholder_Chan[] = _("ちゃん");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("サファイア");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("ルビー");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("エメラルド");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("アクアだん");
const u8 gText_ExpandedPlaceholder_Magma[] = _("マグマだん");
const u8 gText_ExpandedPlaceholder_Archie[] = _("アオギリ");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("マツブサ");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("カイオーガ");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("グラードン");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("ユウキ");
const u8 gText_ExpandedPlaceholder_May[] = _("ハルカ");
const u8 gText_ExpandedPlaceholder_Red[] = _("レッド");
const u8 gText_ExpandedPlaceholder_Green[] = _("グリーン");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("タマゴ");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("ポケモン");
const u8 gText_Player[] = _("しゅじんこう"); // Unused
const u8 gText_Pokedex[] = _("ポケモンずかん"); // Unused
const u8 gText_Time[] = _("プレイじかん");
const u8 gText_Badges[] = _("もっているバッジ"); // Unused
const u8 gText_AButton[] = _("エーボタン"); // Unused
const u8 gText_BButton[] = _("ビーボタン"); // Unused
const u8 gText_RButton[] = _("アールボタン"); // Unused
const u8 gText_LButton[] = _("エルボタン"); // Unused
const u8 gText_Start[] = _("スタートボタン"); // Unused
const u8 gText_Select[] = _("セレクトボタン"); // Unused
const u8 gText_ControlPad[] = _("じゅうじボタン"); // Unused
const u8 gText_LButtonRButton[] = _("Lボタン Rボタン"); // Unused
const u8 gText_Controls[] = _(" そうさ せつめい"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}つぎ");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}つぎ {B_BUTTON}もどる");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}つぎ {B_BUTTON}やめる");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}{B_BUTTON}やめる");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}おわる");
const u8 gText_Boy[] = _("おとこ");
const u8 gText_Girl[] = _("おんな");
const u8 gText_ThisIsAPokemon[] = _("ポケットモンスター\n……すなわち ポケモン{PAUSE 96}");
const u8 gText_5MarksPokemon[] = _("?????ポケモン");
const u8 gText_CryOf[] = _("なきごえ");
const u8 gText_SizeComparedTo[] = _("{STR_VAR_1} と {PLAYER}    の おおきさくらべ");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(""); // Unused
const u8 gText_WelcomeToHOF[] = _("でんどういり おめでとう!");
const u8 gText_HOFDexRating[] = _("みつけた ポケモン {STR_VAR_1}!\nつかまえた ポケモン {STR_VAR_2}!\p\nオダマキはかせの\nポケモンずかん ひょうか!\pオダマキどれどれ\p\n");
const u8 gText_HOFDexSaving[] = _("ここまでの レポートを かきしるしています!\nでんげんを きらないでください");
const u8 gText_HOFCorrupted[] = _("でんどういりの きろくが こわれています!");
const u8 gText_HOFNumber[] = _(" だい{STR_VAR_1}かい でんどういり!");
const u8 gText_LeagueChamp[] = _("リーグ チャンピオン! おめでとう!");
const u8 gText_Number[] = _("No. ");
const u8 gText_Level[] = _("Lv");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("なまえ");
const u8 gText_IDNumber[] = _("IDNo.");
const u8 gText_BirchInTrouble[] = _("オダマキはかせが ピンチだ!\nポケモンを だして たすけてあげよう!");
const u8 gText_ConfirmStarterChoice[] = _("このポケモンにしますか?");
const u8 gText_Pokemon4[] = _("ポケモン"); // Unused
const u8 gText_FlyToWhere[] = _("どこへ とびますか?");
const u8 gMenuText_Use[] = _("つかう");
const u8 gMenuText_Toss[] = _("すてる");
const u8 gMenuText_Register[] = _("とうろく");
const u8 gMenuText_Give[] = _("もたせる");
const u8 gMenuText_Confirm[] = _("けってい");
const u8 gText_Cancel[] = _("もどる");
const u8 gText_Cancel2[] = _("やめる");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("なし");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("まえに もどります!");
const u8 gText_WhatWouldYouLike[] = _("なにを しますか?");
const u8 gMenuText_Give2[] = _("あげる");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _("のみ"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1}まい");
const u8 gText_CloseBag[] = _("バッグをとじる");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}を\nどうしますか?");
const u8 gText_CantWriteMail[] = _("ここで メールを\nかくことは できません!");
const u8 gText_NoPokemon[] = _("ポケモンが いませんよ!");
const u8 gText_MoveVar1Where[] = _("{STR_VAR_1}を\nどこに いれますか?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1}を\nもたせることは できません!");
const u8 gText_TossHowManyVar1s[] = _("{STR_VAR_1}を\nいくつ すてますか?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_1}を\n{STR_VAR_2}コ すてました");
const u8 gText_ConfirmTossItems[] = _("{STR_VAR_1}を\n{STR_VAR_2}コ すてても\nよろしいですか?");
const u8 gText_DadsAdvice[] = _("おとうさんの ことば……\n{PLAYER}! こういうものには\lつかいどきが あるんだ!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER}は\n{STR_VAR_2}を つかった!{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("まだ まえに つかった スプレーの\nこうかが のこってます!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("まだ まえに つかった コロンの\nこうかが のこってます!{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("ボックスが いっぱい です{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("フィールド");
const u8 gText_TheBattle[] = _("せんとう");
const u8 gText_ThePokemonList[] = _("ポケモンリスト");
const u8 gText_TheShop[] = _("ショップ");
const u8 gText_ThePC[] = _("パソコン");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("{STR_VAR_1}へ\nもどります");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING(" ど う ぐ  "),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("モンスターボール"),
    [POCKET_TM_HM]      = COMPOUND_STRING(" わざマシン  "),
    [POCKET_BERRIES]    = COMPOUND_STRING(" き の み  "),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("たいせつなもの ")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("かいに きた");
const u8 gText_ShopSell[] = _("うりに きた");
const u8 gText_ShopQuit[] = _("なんでもないです");
const u8 gText_ThatItemIsSoldOut[] = _("すみません もう うりきれです{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("うりきれ");
const u8 gText_InBagVar1[] = _("もってるかず {STR_VAR_1}コ");
const u8 gText_QuitShopping[] = _("かいもの を やめます");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1} を\nいくつ おかいあげに なりますか?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1} {STR_VAR_2} を\nいくつ おかいあげに なりますか?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}を {STR_VAR_2}コで\n{STR_VAR_3}円 おかいあげですか?");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1} だね!\n{STR_VAR_2}円 だけど かうかい?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("{STR_VAR_1} ですね!\n{STR_VAR_2}円 だけど かいますか?");
const u8 gText_HereYouGoThankYou[] = _("はい まいど!\nありがとう ございます");
const u8 gText_ThankYouIllSendItHome[] = _("どうも ありがとう!\nじたくの パソコンに おくって おきますね!");
const u8 gText_ThanksIllSendItHome[] = _("どうも ありがとう!\nじたくの パソコンに おくって おくね!");
const u8 gText_YouDontHaveMoney[] = _("おかねが たりないですよ!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("それ いじょう\nもちきれない ですよ!{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("{STR_VAR_1} を\nいれる ばしょが いっぱいです{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("その ほかに わたしどもで\nなにか おちからに なれることは?");
const u8 gText_CanIHelpWithAnythingElse [] = _("その ほかに\nなにか ちからに なれることは?");
const u8 gText_ThrowInPremierBall[] = _("プレミアボール 1コ\nおまけ しておきますね!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("プレミアボール {STR_VAR_1}コ\nおまけ しておきますね!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}を\nかいとるわけには いきません!{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}を\nいくつ うりますか?");
const u8 gText_ICanPayVar1[] = _("{STR_VAR_1}円で ひきとらせて いただきます\nよろしいですか?");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2} を わたして\n{STR_VAR_1}円 うけとった!");
const u8 gText_PokedollarVar1[] = _("{STR_VAR_1}円");
const u8 gText_HP3[] = _("たいりょく");
const u8 gText_SpAtk3[] = _("とくこう");
const u8 gText_SpDef3[] = _("とくぼう");
const u8 gText_WontHaveEffect[] = _("つかっても こうかがないよ{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("どの ポケモンと がったい しますか ?");
const u8 gText_CantBeUsedOnPkmn[] = _("そのポケモンには\nつかえません{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1}を もどすことが\nできない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}は すでに\nせんとうに でています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1}は すでに\nせんたく されています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1}は たたかうための\nげんきが のこっていません!!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("{STR_VAR_1}の ポケモンは じぶんの\nポケモンと いれかえることは できません!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("タマゴを\nせんとうに だすことは できません!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("あたらしい バッジを てにするまで\nまだ つかえません{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("さんか できる ポケモンは\n{STR_VAR_1}ひき まで です!{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("とった メールを パソコンに\nてんそうしますか?");
const u8 gText_MailSentToPC[] = _("メールを パソコンに\nてんそうしました{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("パソコンの メールボックスが\nいっぱいです!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("メールを とると メッセージが\nきえてしまいますが よろしいですか?");
const u8 gText_RemoveMailBeforeItem[] = _("メールを はずさないと\nどうぐは もてません!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1}に\n{STR_VAR_2}を もたせた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1}は すでに\n{STR_VAR_2}を もっています\pもっている どうぐを\nとりかえますか?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1}は なにも\nどうぐを もって いません!{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_1}から\n{STR_VAR_2}を あずかりました{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("ポケモンから メールを\nとりました!{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2}を あずかって\nあらたに {STR_VAR_1}を もたせました!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("すでに どうぐを もっているので\nメールを もたせることが できません{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("ボックスから メールを うつしました{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("バッグが いっぱいで\nポケモンの どうぐを うけとれません!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえた!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1}と {STR_VAR_2}は\nあいしょうが わるかった!\p{STR_VAR_2}は おぼえられない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえたい……!\pしかし {STR_VAR_1}は わざを 4つ\nおぼえるので せいいっぱいだ!\p{STR_VAR_2}の かわりに\nほかの わざを わすれさせますか?");
const u8 gText_StopLearningMove2[] = _("それでは…… {STR_VAR_2}を\nおぼえるのを あきらめますか?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1}は {STR_VAR_2}を\nおぼえずに おわった!{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("どの わざを\nわすれさせたい?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1 {PAUSE 15}2の {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン!\p{STR_VAR_1}は {STR_VAR_2}の\nつかいかたを きれいに わすれた!\pそして……!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1}は すでに\n{STR_VAR_2}を おぼえています{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}の たいりょくが\n{STR_VAR_2} かいふくした{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1}の どくは\nきれい さっぱり なくなった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1}の からだの\nしびれが とれた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1}は\nめを さました{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}の\nやけどが なおった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}の からだの\nしもやけが なおった{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1}の からだの\nこおりが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("わざポイントが\nかいふくした!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1}は\nげんきを とりもどした!{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1}は\nけんこうになった!{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}の\nわざポイントが ふえた!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1}の\nレベルが {STR_VAR_2}になった!");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1}は {STR_VAR_2}の けいけんちを もらい\nレベル {STR_VAR_3}に あがった!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}の {STR_VAR_2}の\nきそ ポイントが あがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1}が ちょっと なついた!\n{STR_VAR_2}の きそポイントが さがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1}は さいこうに なついている!\n{STR_VAR_2}の きそポイントが さがった!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1}は ちょっと なついた\n{STR_VAR_2}の きそポイントは もうさがらない!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1}の\nこんらんが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1}の\nメロメロが とけた{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1}は へんしんした !{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1}を\nすてても よろしいですか");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}を\nすてました{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("どのポケモンに おぼえさせますか?"); // Unused
const u8 gText_ChoosePokemon[] = _("ポケモンを えらんで ください");
const u8 gText_MoveToWhere[] = _("どこに いどうしますか?");
const u8 gText_TeachWhichPokemon[] = _("どのポケモンに おしえますか?");
const u8 gText_UseOnWhichPokemon[] = _("どのポケモンに つかいますか?");
const u8 gText_GiveToWhichPokemon[] = _("どのポケモンに もたせますか?");
const u8 gText_DoWhatWithPokemon[] = _("{STR_VAR_1}を どうする?");
const u8 gText_NothingToCut[] = _("きれるものが ありません!");
const u8 gText_CantSurfHere[] = _("ここでは のれません");
const u8 gText_AlreadySurfing[] = _("すでに なみのり しています");
const u8 gText_CantUseHere[] = _("ここでは つかえません");
const u8 gText_RestoreWhichMove[] = _("どれを かいふくする?");
const u8 gText_BoostPP[] = _("どれを ふやす?");
const u8 gText_DoWhatWithItem[] = _("もちものを どうしますか?");
const u8 gText_NoPokemonForBattle[] = _("これでは たたかえません!");
const u8 gText_ChoosePokemon2[] = _("どのポケモンを あずけますか?");
const u8 gText_NotEnoughHp[] = _("たいりょくが たりません……");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1}ひき そろっていません");
const u8 gText_PokemonCantBeSame[] = _("おなじ ポケモンが います!");
const u8 gText_NoIdenticalHoldItems[] = _("おなじ どうぐを もってます");
const u8 gText_CurrentIsTooFast[] = _("ながれが はやくて ダメだ!");
const u8 gText_DoWhatWithMail[] = _("メールを どうしますか?");
const u8 gText_ChoosePokemonCancel[] = _("ポケモンか もどるを せんたく");
const u8 gText_ChoosePokemonConfirm[] = _("ポケモンを えらんで けってい!");
const u8 gText_SendWhichMonToPC[] = _("どの ポケモンを PCへ おくりますか ?");
const u8 gText_MoveItemWhere[] = _("どうぐを どこへ うごかしますか ?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}の {STR_VAR_2}と\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}の {STR_VAR_2}を いれかえた !{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("サイクリングを たのしもう!");
const u8 gText_InUseAlready_PM[] = _("すでに つかっています!");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1}は\n{STR_VAR_2}を もっています");
const u8 gText_WhichAppliance[] = _("どの かでんを\nちゅうもん しますか?");
const u8 gText_NoUse[] = _("つかえません");
const u8 gText_Able[] = _("さんかしない");
const u8 gText_First_PM[] = _("いちばんめ");
const u8 gText_Second_PM[] = _("にばんめ");
const u8 gText_Third_PM[] = _("さんばんめ");
const u8 gText_Able2[] = _("でられます");
const u8 gText_NotAble[] = _("でられません");
const u8 gText_Able3[] = _("おぼえられる!");
const u8 gText_NotAble2[] = _("おぼえられない");
const u8 gText_Learned[] = _("もうおぼえてる");
const u8 gText_Have[] = _("もっている");
const u8 gText_DontHave[] = _("もっていない");
const u8 gText_Fourth[] = _("よんばんめ");
const u8 gText_PkmnCantParticipate[] = _("その ポケモンは さんか できません{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("さんかを やめますか?");
const u8 gText_CancelBattle[] = _("たいせんを やめますか?");
const u8 gText_ReturnToWaitingRoom[] = _("ひかえしつに もどりますか?");
const u8 gText_CancelChallenge[] = _("ちょうせんを やめますか?");
const u8 gText_EscapeFromHere[] = _("ここを だっしゅつ して\n{STR_VAR_1}に もどる?");
const u8 gText_ReturnToHealingSpot[] = _("さいごに やすんだ\n{STR_VAR_1}に テレポートする?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("そのポケモンを こうかんすると\nせんとうできなくなっちゃうよ!");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("その ポケモンは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("その ポケモンは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("タマゴは いま\nこうかんに だせません");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("あいての ポケモンとは\nいまは こうかん できません");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("いまは そのポケモンを \nあいては うけとることが できません");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("その あいてとは いまは\nこうかん できません");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("あいての ほしがっている タイプの\nポケモンでは ありません");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("それは タマゴでは ありません");
const u8 gText_Register[] = _("とうろくする");
const u8 gText_Attack3[] = _("こうげき");
const u8 gText_Defense3[] = _("ぼうぎょ");
const u8 gText_SpAtk4[] = _("とくこう");
const u8 gText_SpDef4[] = _("とくぼう");
const u8 gText_Speed2[] = _("すばやさ");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _("あと"); // Unused
const u8 gText_OTSlash[] = _("おや/");
const u8 gText_RentalPkmn[] = _("レンタルポケモン");
const u8 gText_TypeSlash[] = _("タイプ/");
const u8 gText_Power[] = _("いりょく");
const u8 gText_Accuracy2[] = _("めいちゅう");
const u8 gText_Appeal[] = _("アピール");
const u8 gText_Jam[] = _("ぼうがい");
const u8 gText_Status[] = _("じょうたい");
const u8 gText_ExpPoints[] = _("げんざいのけいけんち");
const u8 gText_NextLv[] = _("レベルアップまで");
const u8 gText_RibbonsVar1[] = _("げんざい  {STR_VAR_1}こ");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("イベント"); // Unused
const u8 gText_Switch[] = _("いれかえ");
const u8 gText_PkmnInfo[] = _("ポケモンじょうほう");
const u8 gText_PkmnSkills[] = _("ポケモンのうりょく");
const u8 gText_BattleMoves[] = _("たたかうわざ");
const u8 gText_ContestMoves[] = _("コンテストわざ");
const u8 gText_Info[] = _("きりかえ");
const u8 gText_EggWillTakeALongTime[] = _("この タマゴは\nうまれるまで かなり かかりそう");
const u8 gText_EggWillTakeSomeTime[] = _("なにが うまれて くるのかな?\nうまれる まで まだまだ かかりそう");
const u8 gText_EggWillHatchSoon[] = _("ときどき うごいて いるようだ\nうまれる まで もうちょっと かな?");
const u8 gText_EggAboutToHatch[] = _("なかから おとが きこえてくる\nもうすぐ うまれそう!");
const u8 gText_HMMovesCantBeForgotten2[] = _("それは たいせつなわざです\nわすれさせることは できません!");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であった");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で かえった");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく \nつうしんこうかんに よって であった");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nうんめいてきな であいを した");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}で であったようだ");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで であった");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}せいかく {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}のとき\nどこかで かえった");
const u8 gText_OddEggFoundByCouple[] = _("そだてや ふうふ から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_PeculiarEggNicePlace[] = _("ステキな ばしょで てにいれた\nふしぎな ふしぎな ポケモンのタマゴ");
const u8 gText_PeculiarEggTrade[] = _("つうしんこうかんで てにいれた\nふしぎな ポケモンのタマゴ");
const u8 gText_EggFromHotSprings[] = _("おんせんばあさん から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_EggFromTraveler[] = _("たびの おじさん から もらった\nふしぎな ポケモンのタマゴ");
const u8 gText_ApostropheSBase[] = _(" きち");
const u8 gText_OkayToDeleteFromRegistry[] = _("{STR_VAR_1} の とうろくを\nかいじょ しても よろしい ですか?");
const u8 gText_RegisteredDataDeleted[] = _("とうろくを かいじょ しました{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("とうろく リストは ありません{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("とうろく かいじょ");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("グッズを おく");
const u8 gText_PutAway[] = _("グッズを もどす");
const u8 gText_Toss2[] = _("グッズを すてる");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("えらんだ グッズを へやに おきます!");
const u8 gText_StoreChosenDecorInPC[] = _("えらんだ グッズを パソコンに もどします!");
const u8 gText_ThrowAwayUnwantedDecors[] = _("いらなくなった グッズを すてます!");
const u8 gText_NoDecorations[] = _("グッズは ありません!{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("つくえ");
const u8 gText_Chair[] = _("いす");
const u8 gText_Plant[] = _("うえき");
const u8 gText_Ornament[] = _("おきもの");
const u8 gText_Mat[] = _("マット");
const u8 gText_Poster[] = _("ポスター");
const u8 gText_Doll[] = _("ぬいぐるみ");
const u8 gText_Cushion[] = _("クッション");
const u8 gText_Gold[] = _("きん");
const u8 gText_Silver[] = _("ぎん");
const u8 gText_PlaceItHere[] = _("ここに おきますか?");
const u8 gText_CantBePlacedHere[] = _("ここには おけません!");
const u8 gText_CancelDecorating[] = _("おくのを やめますか?");
const u8 gText_InUseAlready[] = _("すでに おかれて います!");
const u8 gText_NoMoreDecorations[] = _("これいじょう おけません\nひみつきちに おけるのは {STR_VAR_1}こ までです");
const u8 gText_NoMoreDecorations2[] = _("これいじょう おけません\nへやに おけるのは {STR_VAR_1}こ までです");
const u8 gText_MustBePlacedOnDesk[] = _("ここには おけません!\nつくえの うえなどに おいてください!"); // Unused
const u8 gText_CantPlaceInRoom[] = _("この グッズは\nじぶんの へやには おけません!");
const u8 gText_CantThrowAwayInUse[] = _("このグッズは おかれて いるので\nすてる ことが できません!");
const u8 gText_DecorationWillBeDiscarded[] = _("{STR_VAR_1} は なくなりますが\nよろしい ですか?");
const u8 gText_DecorationThrownAway[] = _("グッズを すてました!");
const u8 gText_StopPuttingAwayDecorations[] = _("もどすのを やめますか?");
const u8 gText_NoDecorationHere[] = _("ここに グッズは ありません!");
const u8 gText_ReturnDecorationToPC[] = _("このグッズを パソコンに もどしますか?");
const u8 gText_DecorationReturnedToPC[] = _("グッズを パソコンに もどしました!");
const u8 gText_NoDecorationsInUse[] = _("グッズは おかれて いません!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("なにも ありません!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("メールは 1つうも ありません{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("{STR_VAR_1} の\nメールを どうしますか?");
const u8 gText_MessageWillBeLost[] = _("ないようは きえてしまいますが\nよろしいですか?");
const u8 gText_BagIsFull[] = _("バッグが いっぱいです!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("ないようを けした メールを\nバッグに いれました{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("パパ");
const u8 gText_Mom[] = _("ママ");
const u8 gText_CoolnessContest[] = _("かっこよさコンテスト");
const u8 gText_BeautyContest[] = _("うつくしさコンテスト");
const u8 gText_CutenessContest[] = _("かわいさコンテスト");
const u8 gText_SmartnessContest[] = _("かしこさコンテスト");
const u8 gText_ToughnessContest[] = _("たくましさコンテスト");
const u8 gText_Information[] = _("おしらせ");
const u8 gText_Yes[] = _("はい");
const u8 gText_No[] = _("いいえ");
const u8 gText_Lv50[] = _("レベル50");
const u8 gText_OpenLevel[] = _("オープンレベル");
const u8 gText_BattleFrontier[] = _("バトルフロンティア");
const u8 gText_Cool[] = _("かっこよさ");
const u8 gText_Beauty[] = _("うつくしさ");
const u8 gText_Cute[] = _("かわいさ");
const u8 gText_Smart[] = _("かしこさ");
const u8 gText_Tough[] = _("たくましさ");
const u8 gText_Normal[] = _("ノーマル");
const u8 gText_Super[] = _("スーパー");
const u8 gText_Hyper[] = _("ハイパー");
const u8 gText_Master[] = _("マスター");
const u8 gText_SomeonesPC[] = _("だれかのパソコン");
const u8 gText_LanettesPC[] = _("マユミのパソコン");
const u8 gText_BillsPc[] = _("マサキのパソコン");
const u8 gText_PlayersPC[] = _("{PLAYER}のパソコン");
const u8 gText_HallOfFame[] = _("でんどういり");
const u8 gText_LogOff[] = _("スイッチをきる");
const u8 gText_Single2[] = _("シングル");
const u8 gText_Double2[] = _("ダブル");
const u8 gText_Multi[] = _("マルチ");
const u8 gText_MultiLink[] = _("つうしん マルチ");
const u8 gText_MenuOptionPokedex[] = _("ずかん");
const u8 gText_MenuOptionPokemon[] = _("ポケモン");
const u8 gText_MenuOptionBag[] = _("バッグ");
const u8 gText_MenuOptionPokenav[] = _("ポケナビ");
const u8 gText_MenuOptionSave[] = _("レポート");
const u8 gText_MenuOptionOption[] = _("せってい");
const u8 gText_MenuOptionExit[] = _("とじる");
const u8 gText_SouthernIsland[] = _("みなみのことう");
const u8 gText_BirthIsland[] = _("たんじょうのしま");
const u8 gText_FarawayIsland[] = _("さいはてのことう");
const u8 gText_NavelRock[] = _("へそのいわ");
const u8 gText_NormalTagMatch[] = _("ふつうタッグ");
const u8 gText_VarietyTagMatch[] = _("いろいろタッグ");
const u8 gText_UniqueTagMatch[] = _("ユニークタッグ");
const u8 gText_ExpertTagMatch[] = _("エキスパートタッグ");
const u8 gText_BattleBasics[] = _("たたかいの きほん");
const u8 gText_PokemonNature[] = _("ポケモンのせいかく");
const u8 gText_PokemonMoves[] = _("ポケモンのわざ");
const u8 gText_Underpowered[] = _("ちからをはっきできない");
const u8 gText_WhenInDanger[] = _("ピンチになったら");
const u8 gText_BattlePokemon[] = _("でてくるポケモン");
const u8 gText_BattleTrainers[] = _("たたかう トレーナー");
const u8 gText_1F[] = _("1かい");
const u8 gText_2F[] = _("2かい");
const u8 gText_3F[] = _("3かい");
const u8 gText_4F[] = _("4かい");
const u8 gText_5F[] = _("5かい");
const u8 gText_6F[] = _("6かい");
const u8 gText_7F[] = _("7かい");
const u8 gText_8F[] = _("8かい");
const u8 gText_9F[] = _("9かい");
const u8 gText_10F[] = _("10かい");
const u8 gText_11F[] = _("11かい");
const u8 gText_B1F[] = _("ちか1かい");
const u8 gText_B2F[] = _("ちか2かい");
const u8 gText_B3F[] = _("ちか3かい");
const u8 gText_B4F[] = _("ちか4かい");
const u8 gText_Rooftop[] = _("おくじょう");
const u8 gText_ElevatorNowOn[] = _("げんざいのフロア");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("ランキングホール");
const u8 gText_ExchangeService[] = _("ひきかえサービス");
const u8 gText_SlateportCity[] = _("カイナシティ");
const u8 gText_Exit[] = _("やめる");
const u8 gText_YourPartysFull[] = _("てもちが いっぱいです !{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("てもち");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("4つの ことばを くみあわせて");
const u8 gText_AndMakeYourProfile[] = _("プロフィールを つくろう!");
const u8 gText_CombineSixWordsOrPhrases[] = _("6つの ことばで");
const u8 gText_AndMakeAMessage[] = _("メッセージを つくろう!");
const u8 gText_FindWordsThatDescribeYour[] = _("いまの きもちに ぴったりあう");
const u8 gText_FeelingsRightNow[] = _("ことばを みつけよう!");
const u8 gText_WithFourPhrases[] = _("4つの ことばで"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("9つの ことばを くみあわせて");
const u8 gText_AndMakeAMessage2[] = _("メッセージを つくろう!");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("ことばを 1つだけ いれかえて");
const u8 gText_AndImproveTheBardsSong[] = _("オヤジのうたを よくして あげよう!");
const u8 gText_YourProfile[] = _("プロフィールは");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("たいせんが はじまるときの きもちは");
const u8 gText_WhatYouSayIfYouWin[] = _("たいせんに かったときの あいさつは");
const u8 gText_WhatYouSayIfYouLose[] = _("たいせんに まけたときの あいさつは");
const u8 gText_TheAnswer[] = _("こたえは");
const u8 gText_TheMailMessage[] = _("メールに のせる メッセージは");
const u8 gText_TheMailSalutation[] = _("はがきに のせる あいさつは"); // Unused
const u8 gText_TheBardsSong2[] = _("あたらしい うたは");
const u8 gText_CombineTwoWordsOrPhrases[] = _("2つの ことばを くみあわせて");
const u8 gText_AndMakeATrendySaying[] = _("はやらせたい ことばを つくろう!");
const u8 gText_TheTrendySaying[] = _("はやらせたい ことばは");
const u8 gText_IsAsShownOkay[] = _("これで いいですか?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("2つの ことばを くみあわせて");
const u8 gText_ToTeachHerAGoodSaying[] = _("いい ことばを おしえてあげよう!");
const u8 gText_FindWordsWhichFit[] = _("トレーナーの イメージに");
const u8 gText_TheTrainersImage[] = _("ぴったりの ことばを みつけよう!");
const u8 gText_TheImage[] = _("イメージは");
const u8 gText_OutOfTheListedChoices[] = _("ことばの なかから");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("クイズの こたえを えらぼう!");
const u8 gText_AndCreateAQuiz[] = _("クイズを つくろう!");
const u8 gText_PickAWordOrPhraseAnd[] = _("ことばの なかから ひとつを えらんで");
const u8 gText_SetTheQuizAnswer[] = _("クイズの こたえを つくろう!");
const u8 gText_TheAnswerColon[] = _("こたえは");
const u8 gText_TheQuizColon[] = _("クイズは"); // Unused
const u8 gText_ApprenticePhrase[] = _("でしの きめゼリフは");
const u8 gText_QuitEditing[] = _("へんしゅうを やめますか ?");
const u8 gText_StopGivingPkmnMail[] = _("メールを もたせるのを やめますか?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("ショップの アンケートに こたえよう!");
const u8 gText_LetsReplyToTheInterview[] = _("インタビューに こたえよう !");
const u8 gText_AllTextBeingEditedWill[] = _("へんしゅうちゅうの ことばを");
const u8 gText_BeDeletedThatOkay[] = _("ぜんぶ けしても いいですか?");
const u8 gText_QuitEditing2[] = _("へんしゅうを やめますか ?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("へんしゅうした ことばは ほぞん"); // Unused
const u8 gText_IsThatOkay[] = _("されませんが いいですか?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("なにか ことばを いれてください!"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("ことばを ぜんぶ けすことは できません!");
const u8 gText_OnlyOnePhrase[] = _("かえられる ことばは 1つ までです!");
const u8 gText_OriginalSongWillBeUsed[] = _("うたを もとに もどします!");
const u8 gText_ThatsTrendyAlready[] = _("それは もう はやっています !"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("2つの ことばを くみあわせてください!");
const u8 gText_QuitGivingInfo[] = _("ことばを おしえるのを やめますか?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("メールを もたせるのを やめますか?"); // Unused
const u8 gText_CreateAQuiz2[] = _("もんだいを つくってください!"); // Unused
const u8 gText_SetTheAnswer[] = _("こたえを えらんでください!"); // Unused
const u8 gText_CancelSelection[] = _("もとにもどして いいですか?"); // Unused
const u8 gText_Profile[] = _("プロフィール");
const u8 gText_AtTheBattlesStart[] = _("たいせんが はじまるとき");
const u8 gText_UponWinningABattle[] = _("たいせんに かったとき");
const u8 gText_UponLosingABattle[] = _("たいせんに まけたとき");
const u8 gText_TheBardsSong[] = _("オヤジのうた");
const u8 gText_WhatsHipAndHappening[] = _("はやっている ものは?");
const u8 gText_Interview[] = _("インタビュー");
const u8 gText_GoodSaying[] = _("いい ことば");
const u8 gText_FansQuestion[] = _("ファンのしつもん");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは ?"); // Unused
const u8 gText_ApprenticesPhrase[] = _("でしの きめゼリフ");
const u8 gText_Questionnaire[] = _("アンケート");
const u8 gText_YouCannotQuitHere[] = _("ここでは とちゅうで");
const u8 gText_SectionMustBeCompleted[] = _("やめることは できません!");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0} さんの クイズ");
const u8 gText_Lady[] = _("おねえさん");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("もんだいを よんだら");
const u8 gText_QuestionPressTheAButton[] = _("Aボタンを おしてね!");
const u8 gText_TheQuizAnswerIs[] = _("クイズの こたえは?");
const u8 gText_LikeToQuitQuiz[] = _("クイズの チャレンジを");
const u8 gText_ChallengeQuestionMark[] = _("あきらめますか?");
const u8 gText_IsThisQuizOK[] = _("クイズは これで いいですか?");
const u8 gText_CreateAQuiz[] = _("もんだいを つくってください!");
const u8 gText_SelectTheAnswer[] = _("こたえを えらんでください!");
const u8 gText_LyricsCantBeDeleted[] = _("かしを けすことは できません!");
const u8 gText_PokemonLeague[] = _("ポケモンリーグ");
const u8 gText_PokemonCenter[] = _("ポケモンセンター");
const u8 gText_Coolness[] = _("かっこよさ ");
const u8 gText_Beauty3[] = _("うつくしさ ");
const u8 gText_Cuteness[] = _("かわいさ ");
const u8 gText_Smartness[] = _("かしこさ ");
const u8 gText_Toughness[] = _("たくましさ ");

const u8 gText_SaveFailedCheckingBackup[] = _("レポートの かきこみに しっぱいしました\nバックアップカートリッジの けんさをします\nしばらくおまちください{COLOR RED}『1ふんほど かかります』");
const u8 gText_BackupMemoryDamaged[] = _("バックアップきのうの こしょう または じゅみょうが\nきました。セーブすることは できませんが このまま\nゲームを あそぶことはできます");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}『このまま ぼうけんをつづけることは できません\nタイトルに もどります』");
const u8 gText_CheckCompleted[] = _("けんさが しゅうりょうしました!\nもういちど レポートを かきこみます\nしばらくおまちください");
const u8 gText_SaveCompleteGameCannotContinue[] = _("レポートの かきこみは しゅうりょうしました\n{COLOR RED}このまま ぼうけんをつづけることは できません\nタイトルに もどります");
const u8 gText_SaveCompletePressA[] = _("レポートの かきこみは しゅうりょうしました\n{COLOR RED}Aボタンを おしてください");

const u8 gText_Ferry[] = _("れんらくせん");
const u8 gText_SecretBase[] = _("ひみつきち");
const u8 gText_Hideout[] = _("アジト");
const u8 gText_ResetRTCConfirmCancel[] = _("RTCをリセットします\nAで けってい Bで キャンセル");
const u8 gText_PresentTime[] = _("げんざいの ゲームない じかん");
const u8 gText_PreviousTime[] = _("ぜんかいの ゲームない じかん");
const u8 gText_PleaseResetTime[] = _("じかんを さいせってい してください");
const u8 gText_ClockHasBeenReset[] = _("じかんを さいせってい しました!\nレポートを かいています おまちください");
const u8 gText_SaveCompleted[] = _("レポートを かきこみました!");
const u8 gText_SaveFailed[] = _("レポートの かきこみに\nしっぱい しました…");
const u8 gText_NoSaveFileCantSetTime[] = _("レポートが ないので\nじかんの せっていは できません!");
const u8 gText_InGameClockUsable[] = _("ゲームない じかんの しゅうせい システムが\nつかえる ように なりました!");
const u8 gText_Spicy2[] = _("から");
const u8 gText_Dry2[] = _("しぶ");
const u8 gText_Sweet2[] = _("あま");
const u8 gText_Bitter2[] = _("にが");
const u8 gText_Sour2[] = _("すっぱ");
const u8 gText_Single[] = _("シングル");
const u8 gText_Double[] = _("ダブル");
const u8 gText_Knockout[] = _("ノックアウト");
const u8 gText_Mixed[] = _("ミックス");
const u8 gText_First[] = _("1ばんめ");
const u8 gText_Second[] = _("2ばんめ");
const u8 gText_Third[] = _("3ばんめ");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}は ちからつきた\p");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}は なんとか どくにたえた\nどくが きえさった!\p");
#endif
const u8 gText_Marco[] = _("コウジ");
const u8 gText_TrainerCardName[] = _("なまえ ");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("おこづかい");
const u8 gText_PokeDollar[] = _("円"); // Unused
const u8 gText_TrainerCardPokedex[] = _("ポケモンずかん");
const u8 gText_EmptyString6[] = _("ひき");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _("てん"); // Unused
const u8 gText_TrainerCardTime[] = _("プレイじかん");
const u8 gJPText_BattlePoints[] = _("ゲームポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}のトレーナーカード");
const u8 gText_HallOfFameDebut[] = _("はじめてのでんどういり");
const u8 gText_LinkBattles[] = _("つうしんたいせん");
const u8 gText_LinkCableBattles[] = _("ケーブルたいせん");
const u8 gText_WinsLosses[] = _("かち:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  まけ:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("ポケモンつうしんこうかん");
const u8 gText_UnionTradesAndBattles[] = _("ユニオンたいせんとこうかん");
const u8 gText_BerryCrush[] = _("きのみクラッシュ");
const u8 gText_WaitingTrainerFinishReading[] = _("あいてが カードを みおわるのを\nまっています");
const u8 gText_PokeblocksWithFriends[] = _("ともだちと つくった ポロック");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("ともだちとコンテスト ゆうしょう");
const u8 gText_BattlePtsWon[] = _("かちとった バトルポイント");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("バトルタワー");
const u8 gText_WinsStraight[] = _("かち/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  れんしょう/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("バトルタワー");
const u8 gText_BattleDome[] = _("バトルドーム");
const u8 gText_BattlePalace[] = _("バトルパレス");
const u8 gText_BattleFactory[] = _("バトルファクトリー");
const u8 gText_BattleArena[] = _("バトルアリーナ");
const u8 gText_BattlePike[] = _("バトルチューブ");
const u8 gText_BattlePyramid[] = _("バトルピラミッド");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} シングル");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} ダブル");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} マルチ");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} つうしん");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("もたせるべき");
const u8 gText_NoNeed[] = _("もたせない");
const u8 gText_AnnouncingResults[] = _("けっか はっぴょう!");
const u8 gText_PreliminaryResults[] = _("1じしんさの けっか!");
const u8 gText_Round2Results[] = _("2じしんさの けっか!");
const u8 gText_ContestantsMonWon[] = _("ゆうしょう! {STR_VAR_1}の {STR_VAR_2}!");
const u8 gText_CommunicationStandby[] = _("つうしんたいきちゅう");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("おおもじ"); // ホントは「ひらがな」
const u8 gText_Lower[] = _("こもじ"); // ホントは「カタカナ」
const u8 gText_Others[] = _("そのほか"); // ホントは「ABC」
const u8 gText_Symbols[] = _("きごう");
const u8 gText_Register2[] = _("とうろく");
const u8 gText_Exit2[] = _("とじる");
const u8 gText_QuitChatting[] = _("チャットを やめますか?");
const u8 gText_RegisterTextWhere[] = _("どこに ことばを とうろくしますか?");
const u8 gText_RegisterTextHere[] = _("ここに とうろくしますか?");
const u8 gText_InputText[] = _("ことばを いれて ください!");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} さんが さんかしました!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0}さんが ぬけました");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0} の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0} の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("さんかしゃが いなくなったので\nしゅうりょうします!");
const u8 gText_LeaderLeftEndingChat[] = _("リーダーの {DYNAMIC 0}が\nぬけたので かいさんします!");
const u8 gText_RegisteredTextChangedOKToSave[] = _("とうろくが かわりました\nポケモンレポートに かきこみますか?");
const u8 gText_AlreadySavedFile_Chat[] = _("まえに かかれた レポートに\nうえから かいても いいですか?");
const u8 gText_SavingDontTurnOff_Chat[] = _("ポケモンレポートに かきこんでいます\nでんげんを きらないで ください");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} は\nレポートに しっかり かきのこした!");
const u8 gText_IfLeaderLeavesChatEnds[] = _("リーダーが やめると かいさん\nになりますが よろしいですか?");
const u8 gText_Hello[] = _("こんにちは");
const u8 gText_Pokemon2[] = _("ポケモン");
const u8 gText_Trade[] = _("こうかん");
const u8 gText_Battle[] = _("たいせん");
const u8 gText_Lets[] = _("しよう!");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("ごめん…");
const u8 gText_YaySmileEmoji[] = _("わーい{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("サンキュー");
const u8 gText_ByeBye[] = _("バイバイ!");
const u8 gText_HatchedFromEgg[] = _("タマゴが かえって\n{STR_VAR_1}が うまれた!");
const u8 gText_NicknameHatchPrompt[] = _("うまれた {STR_VAR_1}に\nニックネームを つけますか ?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("きのみクラッシュを はじめます\nつかう きのみを えらんでください\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _(" ほかの メンバーが きのみを\nえらぶまで おまちください");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}サラサラな こなが\n{STR_VAR_1}で できた!{RESUME_MUSIC}\pごうけいで こなの りょうが\n{STR_VAR_2}になった!\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _(" ゲームの けっかを\nポケモンレポートに かきこんでいます\lしばらく おまちください");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("  きのみクラッシュで もういちど\nあそびますか?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("つかう きのみが ありません\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("  ぬけた メンバーが いるので\nゲームを しゅうりょうします");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("  じかんぎれ です\pよいこな が\nできあがり ませんでした\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("  つうしんたいきちゅう");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _(" 1.{COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _(" 1.{DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("   かい");
ALIGNED(4) const u8 gText_XDotY[] = _(" {STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("  {STR_VAR_1}のみ");
ALIGNED(4) const u8 gText_TimeColon[] = _("   じかん");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("おすはやさ");
ALIGNED(4) const u8 gText_Silkiness[] = _("  サラサラぐあい");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" ふん");
ALIGNED(4) const u8 gText_XDotY2[] = _(" {STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("  びょう");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("  かい/びょう");
ALIGNED(4) const u8 gText_Var1Percent[] = _(" {STR_VAR_1}パーセント");
ALIGNED(4) const u8 gText_PressesRankings[] = _("おした かいすう ランキング");
ALIGNED(4) const u8 gText_CrushingResults[] = _(" つぶした けっか");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("   ていねいさ ランキング");
ALIGNED(4) const u8 gText_CoopRankings[] = _("たすけあい ランキング");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("おすつよさ ランキング");
const u8 gText_BerryCrush2[] = _("きのみクラッシュ");
const u8 gText_PressingSpeedRankings[] = _("   おすはやさ ランキング!");
const u8 gText_Var1Players[] = _("   {STR_VAR_1}にんよう");
const u8 gText_SymbolsEarned[] = _("てにいれた シンボル");
const u8 gText_BattleRecord[] = _("たいせんの きろく");
const u8 gText_BattlePoints[] = _("バトルポイント");
const u8 gText_UnusedCancel[] = _("とじる"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("バトルフロンティアの マップを みます");
const u8 gText_CheckTrainerCard[] = _("トレーナーカードを みます");
const u8 gText_ViewRecordedBattle[] = _("きろくした たいせんを みます");
const u8 gText_PutAwayFrontierPass[] = _("フロンティアパスを とじます");
const u8 gText_CurrentBattlePoints[] = _("いま たまっている バトルポイントです");
const u8 gText_CollectedSymbols[] = _("ここに シンボルを あつめます");
const u8 gText_BattleTowerAbilitySymbol[] = _("バトルタワー アビリティシンボル");
const u8 gText_BattleDomeTacticsSymbol[] = _("バトルドーム タクティクスシンボル");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("バトルパレス スピリットシンボル");
const u8 gText_BattleArenaGutsSymbol[] = _("バトルアリーナ ガッツシンボル");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("バトルファクトリー ノウレッジシンボル");
const u8 gText_BattlePikeLuckSymbol[] = _("バトルチューブ ラックシンボル");
const u8 gText_BattlePyramidBraveSymbol[] = _("バトルピラミッド ブレイブシンボル");
const u8 gText_ThereIsNoBattleRecord[] = _("げんざい たいせんきろくは ありません");
const u8 gText_BattleTower3[] = _("バトルタワー");
const u8 gText_BattleDome2[] = _("バトルドーム");
const u8 gText_BattlePalace2[] = _("バトルパレス");
const u8 gText_BattleArena2[] = _("バトルアリーナ");
const u8 gText_BattleFactory2[] = _("バトルファクトリー");
const u8 gText_BattlePike2[] = _("バトルチューブ");
const u8 gText_BattlePyramid2[] = _("バトルピラミッド");
const u8 gText_BattleTowerDesc[] = _("かちぬき ひたすら うえを めざす。\nさいのうを ためされる。");
const u8 gText_BattleDomeDesc[] = _("トーナメントを かちぬく。\nせんじゅつを ためされる。");
const u8 gText_BattlePalaceDesc[] = _("しょうぶを みまもる。\nポケモンとの きずなを ためされる。");
const u8 gText_BattleArenaDesc[] = _("つよい ポケモンの チームで しょうりする。\nとうしを ためされる。");
const u8 gText_BattleFactoryDesc[] = _("レンタルポケモンで しょうりする。\nちしきを ためされる。");
const u8 gText_BattlePikeDesc[] = _("3つの みちから 1つえらび かちすすむ。\nうんを ためされる。");
const u8 gText_BattlePyramidDesc[] = _("ちょうじょうを めざし ぼうけんする。\nゆうきを ためされる。");
const u8 gText_Powder[] = _("きのみのこな");
const u8 gText_BerryPickingRecords[] = _("ドードリオのきのみどりの きろく");
const u8 gText_BerriesPicked[] = _("きのみをとった かいすう");
const u8 gText_BestScore[] = _("さいこう とくてん");
const u8 gText_BerriesInRowFivePlayers[] = _("5にんで きのみを\nつづけてとった かいすう");
const u8 gText_BerryPickingResults[] = _("きのみの けっか はっぴょう!!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("じゅんいの はっぴょう!!");
const u8 gText_AnnouncingPrizes[] = _("しょうひんの はっぴょう!!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("1ばんに なった ひとに\n{DYNAMIC 0}を プレゼント!!");
const u8 gText_CantHoldAnyMore[] = _("{DYNAMIC 0}はいっぱいです…");
const u8 gText_FilledStorageSpace[] = _("{DYNAMIC 0} が いっぱいになってしまった!");
const u8 gText_WantToPlayAgain[] = _("もういちど あそびますか ?");
const u8 gText_SomeoneDroppedOut[] = _("だれかが ぬけました\nつうしんを しゅうりょう します");
const u8 gText_SpacePoints[] = _("てん");
const u8 gText_CommunicationStandby3[] = _("つうしん たいきちゅうです");
const u8 gText_SpacePoints2[] = _("てん");
const u8 gText_SpaceTimes3[] = _("かい");
const u8 gText_PkmnJumpRecords[] = _("ミニポケモンでジャンプの きろく");
const u8 gText_JumpsInARow[] = _("さいこう ジャンプかいすう");
const u8 gText_BestScore2[] = _("さいこう とくてん");
const u8 gText_ExcellentsInARow[] = _("れんぞく EXCELLENT");
const u8 gText_AwesomeWonF701F700[] = _("せいせきが よかったので\n{DYNAMIC 0}を {DYNAMIC 1}こ プレゼント!");
const u8 gText_FilledStorageSpace2[] = _("{DYNAMIC 0} が いっぱいに\nなってしまった!");
const u8 gText_CantHoldMore[] = _("{DYNAMIC 0} は いっぱいです…");
const u8 gText_WantToPlayAgain2[] = _("もういちど あそびますか ?");
const u8 gText_SomeoneDroppedOut2[] = _("だれかがぬけました\nつうしんを しゅうりょうします");
const u8 gText_CommunicationStandby4[] = _("つうしん たいきちゅう");
const u8 gText_LinkContestResults[] = _("{PLAYER}の つうしん コンテスト せいせき");
const u8 gText_1st[] = _("1い");
const u8 gText_2nd[] = _("2い");
const u8 gText_3rd[] = _("3い");
const u8 gText_4th[] = _("4い");
const u8 gText_Friend[] = _("ともだち");
const u8 gText_Pokemon3[] = _("ポケモン"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS} で\nふしぎなもらいものを よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の メニューから\n「つうしん」を えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("「ゲームボーイアドバンスとつうしん」\nを せんたく してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の 「つうしん」を\nえらんで Aボタンを おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの よみこみを\nちゅうし しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん ちゅう です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん エラーです\nせつぞくを たしかめて ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん エラーです\nはじめから やりなおして ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS} に\nカードを よみこませて ください");
const u8 gJPText_ConnectionComplete[] = _("つうしんしゅうりょう!");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな トレーナーが\nホウエンに やってきた!");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ エラー です\nデータが ほぞん できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER} の シングル バトルルーム せいせき");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER} の ダブル バトルルーム せいせき");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER} の マルチ バトルルーム せいせき");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER} の  つうしんマルチ バトルルーム せいせき");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER} の シングル バトルトーナメント せいせき");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER} の ダブル バトルトーナメント せいせき");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER} の シングル バトルホール せいせき");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER} の ダブル バトルホール せいせき");
const u8 gText_BattleChoiceResults[] = _("{PLAYER} の バトルゲーム せいせき");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER} の かちぬきチームバトル せいせき");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER} の バトルトレード シングル せいせき");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER} の バトルトレード ダブル せいせき");
const u8 gText_BattleQuestResults[] = _("{PLAYER} の バトルアドベンチャー せいせき");
const u8 gText_Lv502[] = _("レベル 50");
const u8 gText_OpenLv[] = _("オープンレベル");
const u8 gText_WinStreak[] = _("{STR_VAR_1}れんしょう");
const u8 gText_Current[] = _("げんざい");
const u8 gText_Record[] = _("さいこう");
const u8 gText_Prev[] = _("ぜんかい");
const u8 gText_RentalSwap[] = _("レンタル/こうかん");
const u8 gText_Total[] = _("つうさん");
const u8 gText_ClearStreak[] = _("{STR_VAR_1}れんぱ");
const u8 gText_Championships[] = _("{STR_VAR_1}かい ゆうしょう");
const u8 gText_RoomsCleared[] = _("{STR_VAR_1}へや とっぱ");
const u8 gText_TimesCleared[] = _("{STR_VAR_1}かい クリア");
const u8 gText_KOsInARow[] = _("{STR_VAR_1}にんぬき");
const u8 gText_TimesVar1[] = _("{STR_VAR_1}かい");
const u8 gText_FloorsCleared[] = _("{STR_VAR_1}だん せいは");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("レベル 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("オープンレベル");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("{STR_VAR_2}れんぱ");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("{STR_VAR_2}かい クリア");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("{STR_VAR_2}へや とっぱ");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("{STR_VAR_2}にんぬき");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("{STR_VAR_2}だん せいは");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" ");
const u8 gText_FrontierFacilityIncluding[] = _("");
const u8 gText_FrontierFacilityAreInelegible[] = _("は");

const u8 gText_YesNo[] = _("はい\nいいえ");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("ばあ !");
const u8 gText_CommErrorCheckConnections[] = _("  つうしん エラーが はっせいしました\n   しゅうへんきき との せつぞくを\n    きちんと かくにん してから\n   でんげんを いれなおしてください");
const u8 gText_CommErrorEllipsis[] = _("つうしんエラーが はっせいしました");
const u8 gText_MoveCloserToLinkPartner[] = _(" つうしんあいてと ちかづいて ください\nしょうがいぶつが ないように してください");
const u8 gText_ABtnRegistrationCounter[] = _("Aボタンで うけつけに もどります");
const u8 gText_ABtnTitleScreen[] = _("Aボタンで タイトルに もどります");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}にん せつぞく");
const u8 gText_BronzeCard[] = _("ブロンズ");
const u8 gText_CopperCard[] = _("カッパー");
const u8 gText_SilverCard[] = _("シルバー");
const u8 gText_GoldCard[] = _("ゴールド");
const u8 gText_Day[] = _("にち");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("けってい");
const u8 gText_Days[] = _("にち"); // Unused
const u8 gText_TimeColon2[] = _("じかん:"); // Unused
const u8 gText_GameTime[] = _("ゲームじかん"); // Unused
const u8 gText_RTCTime[] = _("RTCじかん"); // Unused
const u8 gText_UpdatedTime[] = _("なおした じかん"); // Unused
const u8 gText_MenuPokedex[] = _("ずかん");
const u8 gText_MenuPokemon[] = _("ポケモン");
const u8 gText_MenuBag[] = _("バッグ");
const u8 gText_MenuPokenav[] = _("ポケナビ");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("レポート");
const u8 gText_MenuOption[] = _("せってい");
const u8 gText_MenuExit[] = _("とじる");
const u8 gText_MenuRetire[] = _("リタイア");
const u8 gText_MenuRest[] = _("やすむ");
const u8 gText_MenuDexNav[] = _("ずかんナビ");
const u8 gText_SafariBallStock[] = _("サファリボール\nのこり {STR_VAR_1}コ");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nボール  {STR_VAR_3}コ");
const u8 gText_BattlePyramidFloor[] = _("バトルピラミッド\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("げんざい 1だんめ");
const u8 gText_Floor2[] = _("げんざい 2だんめ");
const u8 gText_Floor3[] = _("げんざい 3だんめ");
const u8 gText_Floor4[] = _("げんざい 4だんめ");
const u8 gText_Floor5[] = _("げんざい 5だんめ");
const u8 gText_Floor6[] = _("げんざい 6だんめ");
const u8 gText_Floor7[] = _("げんざい 7だんめ");
const u8 gText_Peak[] = _("げんざい ちょうじょう");
const u8 gText_LinkStandby2[] = _("つうしん たいき ちゅう です\n……Bボタンで キャンセル します");
const u8 gText_PressAToLoadEvent[] = _("Aボタンで できごとを よみこみます\n……Bボタンで キャンセル します");
const u8 gText_LoadingEvent[] = _("できごとを よみこみちゅう!!");
const u8 gText_DontRemoveCableTurnOff[] = _("つうしんケーブルを ぬかないで ください\nでんげんを きらないで ください");
const u8 gText_EventSafelyLoaded[] = _("できごとの よみこみが\nせいじょうに しゅうりょう しました");
const u8 gText_LoadErrorEndingSession[] = _("せつぞく できない ききの ようです\nただしい ききと やりなおしてください");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("ホウエン");
const u8 gText_DexNational[] = _("ぜんこく");
const u8 gText_PokedexDiploma[] = _("{CLEAR 26}プレイヤー{COLOR RED}{SHADOW LIGHT_RED} {PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}   さま\n\n    {STR_VAR_1} ポケモンずかんを\n    みごと かんせい させた\n    いだいなこうせきを たたえ\n    ここに しょうめい します\n\n{CLEAR_TO 80}{COLOR RED}{SHADOW LIGHT_RED}ゲームフリーク");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲームフリーク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("ホウエンちほう");
const u8 gText_Kanto[] = _("カントー");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_1}に\n{STR_VAR_2}を おくります !");
const u8 gText_ByeByeVar1[] = _("ばいばい {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1}から\n{STR_VAR_3}が おくられてきた!");
const u8 gText_TakeGoodCareOfX[] = _("{STR_VAR_3}を かわいがって あげてね!");

const u8 gText_ThreeQuestionMarks[] = _(" ? ? ?");
const u8 gText_MaxHP[] = _("さいだいHP");
const u8 gText_Attack[] = _("こうげき");
const u8 gText_Defense[] = _("ぼうぎょ");
const u8 gText_Speed[] = _("すばやさ");
const u8 gText_SpAtk[] = _("とくこう");
const u8 gText_SpDef[] = _("とくぼう");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("ー");
const u8 gText_MixingRecords[] = _("レコードを まぜています");
const u8 gText_RecordMixingComplete[] = _("しゅうりょう しました\nおつかれさまでした");
const u8 gText_RentalPkmn2[] = _("ポケモンレンタル");
const u8 gText_SelectFirstPkmn[] = _("1ばんめのポケモンを えらんでください");
const u8 gText_SelectSecondPkmn[] = _("2ばんめのポケモンを えらんでください");
const u8 gText_SelectThirdPkmn[] = _("3ばんめのポケモンを えらんでください");
const u8 gText_Rent[] = _("レンタルする");
const u8 gText_Summary[] = _("つよさをみる");
const u8 gText_Others2[] = _("べつのにする");
const u8 gText_Deselect[] = _("はずす");
const u8 gText_TheseThreePkmnOkay[] = _("いじょうの 3ひきで よろしいですか?");
const u8 gText_Yes2[] = _("はい");
const u8 gText_No2[] = _("いいえ");
const u8 gText_CantSelectSamePkmn[] = _("おなじポケモンは えらべません");
const u8 gText_PkmnSwap[] = _("ポケモンこうかん     ");
const u8 gText_SelectPkmnToSwap[] = _("てばなすポケモンを えらんでください");
const u8 gText_SelectPkmnToAccept[] = _("うけとるポケモンを えらんでください");
const u8 gText_Swap[] = _("てばなす");
const u8 gText_Summary2[] = _("つよさをみる");
const u8 gText_Rechoose[] = _("べつのにする");
const u8 gText_QuitSwapping[] = _("こうかんを ちゅうし しますか?");
const u8 gText_Yes3[] = _("はい");
const u8 gText_No3[] = _("いいえ");
const u8 gText_PkmnForSwap[] = _("てばなすポケモン");
const u8 gText_Cancel3[] = _("ちゅうし");
const u8 gText_Swap2[] = _("てばなす"); // Unused
const u8 gText_Accept[] = _("うけとる"); // Unused
const u8 gText_AcceptThisPkmn[] = _("このポケモンを うけとりますか?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("てもちに おなじ ポケモンが います!");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("しゅじんこう");
const u8 gText_SavingBadges[] = _("もっているバッジ");
const u8 gText_SavingPokedex[] = _("ポケモンずかん");
const u8 gText_SavingTime[] = _("プレイじかん");
const u8 gText_WirelessCommStatus[] = _("ワイヤレス つうしん じょうきょう");
const u8 gText_PeopleTrading[] = _("こうかん している ひと:");
const u8 gText_PeopleBattling[] = _("たいせん している ひと:");
const u8 gText_PeopleInUnionRoom[] = _("ユニオンルームに いる ひと:");
const u8 gText_PeopleCommunicating[] = _("つうしん している ひと:");
const u8 gText_F700Players[] = _("{DYNAMIC 0}にん");
const u8 gText_F701Players[] = _("{DYNAMIC 1}にん");
const u8 gText_F702Players[] = _("{DYNAMIC 2}にん");
const u8 gText_F703Players[] = _("{DYNAMIC 3}にん");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("ふしぎなカード");
ALIGNED(4) const u8 gText_WonderNews[] = _("ふしぎなニュース");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("   ジョイスポット");
ALIGNED(4) const u8 gText_Friend2[] = _("ともだち");
ALIGNED(4) const u8 gText_Exit3[] = _("   やめる");
ALIGNED(4) const u8 gText_Receive[] = _("うけとる");
ALIGNED(4) const u8 gText_Send[] = _("おくる");
ALIGNED(4) const u8 gText_Toss[] = _("すてる");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("ワイヤレスで いろいろな できごとを\nよみこみます");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("  もっている ふしぎなカードを\nみることが できます");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("  おくられてきた ニュースを\nみることが できます");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("   タイトルに もどります");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("ふしぎなカードを もっていないので\nあたらしく カードを よみこみます");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("ふしぎなニュースを もっていないので\nあたらしく ニュースを よみこみます");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("  どちらから ふしぎなカードを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("   どちらから ふしぎなニュースを\nよみこみ ますか?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("  つうしん たいき ちゅう です\n...Bボタンで キャンセル します"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _(" つうしん しています...");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("  つうしんが しゅうりょう しました");
ALIGNED(4) const u8 gText_CommunicationError[] = _("  つうしんに しっぱい しました");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("つうしんを キャンセル しました");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("   いまの ふしぎなカードを すてて\nあたらしい カードを よみこみますか?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("   まだ カードの おくりものを もらって\nませんが ほんとうに よみこみますか?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("{STR_VAR_1}から ふしぎなカードが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("{STR_VAR_1}  から ニュースが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _(" あたらしい ふしぎなカードが\nおくられて きました!");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _(" あたらしい ニュースが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewStampReceived[] = _(" あたらしい スタンプが\nおくられて きました!");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _(" あたらしい トレーナーが\nおくられて きました!");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("   おなじふしぎなカードを\nすでにもっています");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("おなじ ニュースを\nすでに もっています");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("   おなじ スタンプを\nすでに もっています");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("   スタンプが いっぱい なので\nもう おせません!");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("   じぶんの きろくを\nジョイスポットに よみこませ ました!");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("  この あいて からは ふしぎなカードを\nうけとれません!");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("  この あいて からは ふしぎなニュースを\nうけとれません!");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("  なにも おくられて\nきません でした");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _(" カードを どうしますか?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("   ニュースを どうしますか?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("  ふしぎなカード を\nおくって います...");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("  ニュースを\nおくって います...");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("{STR_VAR_1}に ふしぎなカードを\nおくり ました!");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("{STR_VAR_1}  に ニュース を\nおくり ました!");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{STR_VAR_1}に スタンプ を\nおくり ました");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{STR_VAR_1}に おくりものを しました!");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("   あいてが おなじ\nふしぎなカードを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("  あいてが おなじ\nニュースを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _(" あいてが おなじ\nスタンプを もっています!");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _(" あいてが つうしんを \nキャンセル しました");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _(" この あいて には\nふしぎなおくりものを わたせません");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("カードをすてると できごとも\nなくなりますが よいですか?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("  ほんとうに ニュースを\nすてても よいですか?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("おくりものを もらってません\nが ほんとうに すてますか?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("  レポートを かいています\nしばらく おまちください");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("  レポートを かきこみました!\nAボタンを おしてください");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("   ふしぎなカードを すてました");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _(" ニュースを すてました");
ALIGNED(4) const u8 gText_MysteryGift[] = _("ふしぎな おくりもの");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}けってい {B_BUTTON}おわる");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}えらぶ {A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gText_PlayersBattleResults[] = _("{PLAYER} の たいせん せいせき");
const u8 gText_TotalRecordWLD[] = _("{STR_VAR_1}しょう {STR_VAR_2}はい {STR_VAR_3}ひきわけ");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 83}かち{CLEAR_TO 128}まけ{CLEAR_TO 176}ひきわけ");
const u8 gText_CommunicationStandby5[] = _("つうしん たいきちゅう...");
const u8 gDaycareText_GetAlongVeryWell[] = _("2ひきの なかは\nとっても よい ようじゃ");
const u8 gDaycareText_GetAlong[] = _("2ひきの なかは\nまずまずの ようじゃ");
const u8 gDaycareText_DontLikeOther[] = _("2ひきの なかは\nそれほど よくないがなぁ");
const u8 gDaycareText_PlayOther[] = _("2ひきは おたがいに\nちがう ポケモンたちと\lあそんでおるがなあ");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("おわる");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("タイムボード");
const u8 gText_TimeCleared[] = _("クリアタイム ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1}ふん  {STR_VAR_2}びょう{STR_VAR_3}");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("{STR_VAR_1}に どの {STR_VAR_3}を\nおしえますか ?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2}を おしえますか ?");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("{STR_VAR_2}を おしえますか ?\n{STR_VAR_3}を 1つ つかいます。");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえた !");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1}は あたらしく\n{STR_VAR_2}を おぼえたい……!\pしかし {STR_VAR_1}は わざを 4つ\nおぼえるので せいいっぱいだ!\p{STR_VAR_2}の かわりに\nほかの わざを わすれさせますか?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("{STR_VAR_2}を おしえるのを\nやめますか ?");
const u8 gText_MoveRelearnerAndPoof[] = _("1 {PAUSE 15}2の {PAUSE 15}…{PAUSE 15}…{PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}ポカン!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1}は {STR_VAR_3}の\nつかいかたを きれいに わすれた!\pそして...\p{STR_VAR_1}は あたらしく {STR_VAR_2}を おぼえた!\n");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1}は\n{STR_VAR_2}を おぼえるのを あきらめた"); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("{STR_VAR_1}に あたらしい わざを\nおしえるのを やめますか ?");
const u8 gText_MoveRelearnerStop[] = _("{STR_VAR_1}に あたらしい わざを\nおぼえさせるのを やめますか ?");;
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("どの わざを\nわすれさせたい?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("たいせんの わざ");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("コンテストわざ");
const u8 gText_MoveRelearnerType[] = _("タイプ/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("いりょく/");
const u8 gText_MoveRelearnerAccuracy[] = _("めいちゅう/");
const u8 gText_MoveRelearnerAppeal[] = _("アピール");
const u8 gText_MoveRelearnerJam[] = _("ぼうがい");
const u8 gText_ClearAllSaveData[] = _("すべての セーブデータエリアを\nクリア しますか?");
const u8 gText_ClearingData[] = _("クリア しています\nおまち ください");
const u8 gText_IsThisTheCorrectTime[] = _("この じかんで よろしいですか ?");
const u8 gText_Confirm3[] = _("けってい");
const u8 gText_Cancel4[] = _("もどる ");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("つうしんたいきちゅう\nあいての せんたくを まっています…");
const u8 gText_BattleWasRefused[] = _("たいせんを ことわられました{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("たいせんを ことわりました{PAUSE 60}");
const u8 gText_NoWeather[] = _("てんきなし"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("はれ"); // Unused
const u8 gText_Sunny2[] = _("はれ2"); // Unused
const u8 gText_Rain[] = _("あめ"); // Unused
const u8 gText_Snow[] = _("ゆき"); // Unused
const u8 gText_Lightning[] = _("かみなり"); // Unused
const u8 gText_Fog[] = _("きり"); // Unused
const u8 gText_VolcanoAsh[] = _("かざんばい"); // Unused
const u8 gText_Sandstorm[] = _("すなあらし"); // Unused
const u8 gText_Fog2[] = _("きり2"); // Unused
const u8 gText_Seafloor[] = _("かいてい"); // Unused
const u8 gText_Cloudy[] = _("くもり"); // Unused
const u8 gText_Sunny3[] = _("はれ3"); // Unused
const u8 gText_HeavyRain[] = _("おおあめ"); // Unused
const u8 gText_Seafloor2[] = _("かいてい2"); // Unused
const u8 gText_DelAll[] = _("ぜんぶけす");
const u8 gText_Cancel5[] = _("やめる");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("クイズ");
const u8 gText_Answer[] = _("こたえ");
const u8 gText_PokeBalls[] = _("ボール");
const u8 gText_Berry[] = _("きのみ");
const u8 gText_Berries[] = _("きのみ");
const u8 gText_ExpShareOn[] = _("がくしゅうそうちを オンに しました{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("がくしゅうそうちを オフに しました{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("ゴースト");
const u8 gText_Boulderbadge[] = _("グレーバッジ");
const u8 gText_Cascadebadge[] = _("ブルーバッジ");
const u8 gText_Thunderbadge[] = _("オレンジバッジ");
const u8 gText_Rainbowbadge[] = _("レインボーバッジ");
const u8 gText_Soulbadge[] = _("ピンクバッジ");
const u8 gText_Marshbadge[] = _("ゴールドバッジ");
const u8 gText_Volcanobadge[] = _("クリムゾンバッジ");
const u8 gText_Earthbadge[] = _("グリーンバッジ");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("オーキド『じぶんの ポケモンを\nくわしく しることも たいせつじゃ !\p");
const u8 gText_OakThisIsListOfPokemon[] = _("これは… {PLAYER}の ポケモンを\nあらわしている ものじゃ\pこれを えらべば ポケモンたちの\nのうりょくや つかえるわざの\lじょうほうを しることが できるぞ\pどうぐを つかいたい ときも\nここで ポケモンを えらぶんじゃ{PAUSE_UNTIL_PRESS}");
